### ISSUE TITLE
null on pulling

### ISSUE THREAD

**Issue by KostyaSha** [KostyaSha/yet-another-docker-plugin#10]
reproduced with system that lost dns and pull_always.

**Comment by KostyaSha** [comment]
```
Will provision 'kostyasha/jenkins-slave:jdk-wget', for label: 'jnlp-docker', in cloud: 'docker'
Jan 14, 2016 10:53:02 PM WARNING com.github.kostyasha.yad.DockerCloud provision
Bad template 'kostyasha/jenkins-slave:jdk-wget' in cloud 'docker': 'null'. Trying next template...
java.lang.NullPointerException
	at com.github.kostyasha.yad.DockerCloud.addProvisionedSlave(DockerCloud.java:259)
	at com.github.kostyasha.yad.DockerCloud.provision(DockerCloud.java:102)
	at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:701)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:305)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:58)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:798)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KostyaSha** [comment]
Maybe was caused by #11

**Comment by KostyaSha** [comment]
Can't reproduce again )

**Comment by KostyaSha** [comment]
Dancing bug.

**Comment by KostyaSha** [comment]
https://github.com/docker-java/docker-java/issues/461

**Comment by KostyaSha** [comment]
Seems caused by ancient docker daemon.

**Comment by KostyaSha** [comment]
backporting fix in progress
