### ISSUE TITLE
Docker slave provisioning fails

### ISSUE THREAD

**Issue by pporada-gl** [KostyaSha/yet-another-docker-plugin#110]
```
YADP 0.1.0-rc29
```
```
[root@365f17e65bac ~]# docker images | grep jenkins-slave
greenlancer/jenkins-slave                 latest              d442745d65e6        7 days ago          2.111 GB
```

```
[root@365f17e65bac ~]# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64
```

```
[root@365f17e65bac ~]# java -version 
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)
```

When using the SSH launcher I receive
```
Nov 10, 2016 5:11:39 PM SEVERE com.github.kostyasha.yad.DockerCloud lambda$provision$0

Error in provisioning; template='DockerSlaveTemplate[id=3413aa87-f92e-43db-9d16-cf0d17aaa061,labelString=docker-slave,launcher=com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher@461caf10,remoteFs=/home/jenkins,maxCapacity=10,mode=EXCLUSIVE,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@64c02363[image=greenlancer/jenkins-slave:latest,pullImage=com.github.kostyasha.yad.commons.DockerPullImage@1a93cb47,createContainer=DockerCreateContainer[command=/opt/entrypoint.sh,hostname=,dnsHosts=[],volumes=[/var/run/docker.sock:/var/run/docker.sock],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=false,memoryLimit=1536,cpuShares=1024,privileged=false,tty=true,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=,links=[]],stopContainer=com.github.kostyasha.yad.commons.DockerStopContainer@27f,removeContainer=com.github.kostyasha.yad.commons.DockerRemoveContainer@5b0f],nodeProperties=[]]' for cloud='Docker Slave'
java.lang.NullPointerException
	at com.github.kostyasha.yad_docker_java.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at com.github.kostyasha.yad_docker_java.com.google.common.net.HostAndPort.fromString(HostAndPort.java:168)
	at com.github.kostyasha.yad_docker_java.com.google.common.net.HostAndPort.fromParts(HostAndPort.java:135)
	at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.getHostAndPort(DockerComputerSSHLauncher.java:151)
	at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:83)
	at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:219)
	at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:120)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

When using the JNLP launcher I receive
```
Nov 10, 2016 5:35:19 PM INFO com.github.kostyasha.yad.DockerCloud provision

Asked to provision load: '1', for: 'docker-slave' label

Nov 10, 2016 5:35:19 PM INFO com.github.kostyasha.yad.DockerCloud provision

Will provision 'greenlancer/jenkins-slave:latest', for label: 'docker-slave', in cloud: 'Docker Slave'

Nov 10, 2016 5:35:19 PM INFO com.github.kostyasha.yad.DockerCloud addProvisionedSlave

Not Provisioning 'greenlancer/jenkins-slave:latest'; Server 'Docker Slave' full with '5' container(s)

Nov 10, 2016 5:35:19 PM INFO com.github.kostyasha.yad.DockerCloud provision

Asked to provision load: '1', for: 'docker-slave' label

Nov 10, 2016 5:35:19 PM INFO com.github.kostyasha.yad.DockerCloud provision

Will provision 'greenlancer/jenkins-slave:latest', for label: 'docker-slave', in cloud: 'Docker Slave'

Nov 10, 2016 5:35:19 PM INFO com.github.kostyasha.yad.DockerCloud addProvisionedSlave

Not Provisioning 'greenlancer/jenkins-slave:latest'; Server 'Docker Slave' full with '5' container(s)
```

**Comment by KostyaSha** [comment]
JNLP is the best way imho. 
- Could you show docker ps - ensure that container was created
- docker log for some failing container?

**Comment by pporada-gl** [comment]
```[root@365f17e65bac ~]# docker ps
CONTAINER ID        IMAGE                              COMMAND                CREATED             STATUS              PORTS                                                      NAMES
aaa6d474da8c        greenlancer/jenkins-slave:latest   "/opt/entrypoint.sh"   31 minutes ago      Up 30 minutes       0.0.0.0:32772->22/tcp                                      evil_heisenberg
fbf3e9051104        greenlancer/jenkins-slave:latest   "/opt/entrypoint.sh"   31 minutes ago      Up 31 minutes       0.0.0.0:32771->22/tcp                                      jolly_dubinsky
8e322c0631c8        greenlancer/jenkins-slave:latest   "/opt/entrypoint.sh"   31 minutes ago      Up 31 minutes       0.0.0.0:32770->22/tcp                                      backstabbing_lamarr
078f8545ba09        greenlancer/jenkins-slave:latest   "/opt/entrypoint.sh"   31 minutes ago      Up 31 minutes       0.0.0.0:32769->22/tcp                                      trusting_brahmagupta
54200d513e78        greenlancer/jenkins-slave:latest   "/opt/entrypoint.sh"   32 minutes ago      Up 32 minutes       0.0.0.0:32768->22/tcp                                      kickass_agnesi
```

I guess because I'm not actually exposing port 50000 in my slaves...

**Comment by KostyaSha** [comment]
with JNLP slave doesn't need expose any port, on docker master maybe...
This slaves created by SSH launcher. Did you set 30 min timeout manually?
Provide `docker inspect` on container this will show network configuration.

**Comment by pporada-gl** [comment]
```
[
    {
        "Id": "aaa6d474da8cd141c77644e19a6ffc1cb59b2699c1666347eda3a47f4f7a783e",
        "Created": "2016-11-10T22:12:09.450765169Z",
        "Path": "/opt/entrypoint.sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 32411,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-11-10T22:12:09.968436962Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:d442745d65e6f0765578ab2b41e138a4921da9707471efdea11cec24fae9c52d",
        "ResolvConfPath": "/var/lib/docker/containers/aaa6d474da8cd141c77644e19a6ffc1cb59b2699c1666347eda3a47f4f7a783e/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/aaa6d474da8cd141c77644e19a6ffc1cb59b2699c1666347eda3a47f4f7a783e/hostname",
        "HostsPath": "/var/lib/docker/containers/aaa6d474da8cd141c77644e19a6ffc1cb59b2699c1666347eda3a47f4f7a783e/hosts",
        "LogPath": "/var/lib/docker/containers/aaa6d474da8cd141c77644e19a6ffc1cb59b2699c1666347eda3a47f4f7a783e/aaa6d474da8cd141c77644e19a6ffc1cb59b2699c1666347eda3a47f4f7a783e-json.log",
        "Name": "/evil_heisenberg",
        "RestartCount": 0,
        "Driver": "devicemapper",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/var/run/docker.sock:/var/run/docker.sock:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "22/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": ""
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 1024,
            "Memory": 1610612736,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 3221225472,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "530",
                "DeviceName": "docker-202:2-10846920-5c5d885fbe34766f1302a998ea67b23a36182c962f8ce9e735907929cde49363",
                "DeviceSize": "10737418240"
            }
        },
        "Mounts": [
            {
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "aaa6d474da8c",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "22/tcp": {}
            },
            "Tty": true,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TFVERSION=0.7.8",
                "TINI_SHA=3cd94f0af6206c70f4639b3971d20d511e5dcd565a0424af2b522598de7227c7"
            ],
            "Cmd": [
                "/opt/entrypoint.sh"
            ],
            "Image": "greenlancer/jenkins-slave:latest",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "build-date": "20161102",
                "cache": "3uij659ubDSGIJFB",
                "com.github.kostyasha.yad.DockerCloud": "Docker Slave",
                "com.github.kostyasha.yad.DockerSlave": "3413aa87-f92e-43db-9d16-cf0d17aaa061",
                "license": "GPLv2",
                "name": "CentOS Base Image",
                "vendor": "CentOS"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "72c6f42301bdeddc62144d3bc9c0ce2c1e3ebacd4df2553fcd58333e4d6129a9",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "22/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32772"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/72c6f42301bd",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "d287b2fb30655b37a2b58da9440444f72895714e7cfbe267e8ae2f39dee99772",
            "Gateway": "10.20.255.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "10.20.255.7",
            "IPPrefixLen": 24,
            "IPv6Gateway": "",
            "MacAddress": "02:42:0a:14:ff:07",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "df502659b9393828358c9545c98cff3d819f72147b65cd463e5e5a5e9c22a909",
                    "EndpointID": "d287b2fb30655b37a2b58da9440444f72895714e7cfbe267e8ae2f39dee99772",
                    "Gateway": "10.20.255.1",
                    "IPAddress": "10.20.255.7",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:14:ff:07"
                }
            }
        }
    }
]
```

**Comment by KostyaSha** [comment]
And here we debugging SSH. :( 
Could you cut all related ssh failure issue into source issue. And here all related JNLP?

**Comment by pporada-gl** [comment]
Ah, I gotcha.

Do you have a location where I can see the Dockerfile for `kostyasha/jenkins-slave`

**Comment by KostyaSha** [comment]
For ssh evarga/jenkins-slave should work as it simple expose SSH with preconfigured user.
For JNLP you may even use https://github.com/KostyaSha/yet-another-docker-plugin/blob/25d28c065f0928970eb8446ef092d435fe47e83c/yet-another-docker-its/src/test/java/com/github/kostyasha/it/tests/SimpleBuildTest.java#L79 
In case of errors for jnlp launcher follow docker log of this container.

**Comment by pporada-gl** [comment]
I'm going to call it a night for now. I will pick this fight with JNLP back up tomorrow. I can see the container launching which is a good thing. I believe I need to fiddle with the jenkins master host and the user.

Thanks for you time so far. I appreciate the help.

**Comment by KostyaSha** [comment]
I can suggest to try jenkins/evarga-slave just to check that your container isn't built in some other way.

**Comment by bjrust** [comment]
I am seeing this exact same issue when using yad plugin and ssh to connect.  I compared my log output and the docker inspect output etc.  A couple of things to note.  I am using the same docker image that I use for a container that I spin up by hand and connect to Jenkins (which works fine).  In addition, if I create a new new node and use the port of one of the docker containers spun up by yad, jenkins connects fine and all is good with that container.  Looking at the inspect and comparing against my hand created container, I see that in the HostConfig->PortBindings section the HostIP is "0.0.0.0" and HostPort is empty on the yad created one and HostIP is empty and HostPort has the port set on my hand run container.  That seems it could be related since the error indicates it fails on a checkNotNull call.  Anyway, any more info on this and can you help me out?
