### ISSUE TITLE
Stressing jenkins by starting multiple jobs in parallel spawn many many slaves until max reached

### ISSUE THREAD

**Issue by clarsonneur** [KostyaSha/yet-another-docker-plugin#112]
Hi,

With yad - 0.1.0-rc28:

Recently, we tried to load jenkins and swarm (UCP). I created 10 identical jobs doing sleep and we tried to start them all in parallel.
The image used is really basic (alpine + java) ready for JNLP connection.
The docker template Max instance is set to 50.

When starting my test, jenkins has queued 10 jobs, and the plugin started to provision slaves against UCP.
about less than 50 slaves has been spawned, while only 10 were used to start the job queue.

at the end of this test, jobs ended and removed 10 slaves. But about 40 persist to be connected to jenkins doing nothing.

NOTE1:  If you start 10 more jobs, 10 of 40s slaves are selected and gets killed.
NOTE2: No slave started by the plugin got issues to start, connect and serve jenkins.

My question:
Are you aware of this strange plugin behavior? We believe it to be a bug.

I can provide the output log to illustrate what happened. (gist)

Thank you

**Comment by clarsonneur** [comment]
I noticed the following log message that tell me that this behavior is may be normal:

```
Nov 15, 2016 12:29:32 PM com.github.kostyasha.yad.DockerCloud provision
INFO: Asked to provision load: '5', for: 'docker' label
[...]
Nov 15, 2016 12:29:45 PM com.github.kostyasha.yad.DockerCloud provision
INFO: Asked to provision load: '9', for: 'docker' label
```

Does this load is a spawn multiplicator to have more nodes than expected to support peak build activity?

Thank you

**Comment by KostyaSha** [comment]
I saw overprovisioning during hpi:run. I thought that it happens during image pull. Also it seems that jenkins do new provisioning calls while previous didn't end, for this AFAIR i set synchronised on provisoining method, but it seems that doesn't help.
 @stephenc i sure that you had overprovisioning issues, how did you debug them?
Also i used your suggest variant with wait slave to become ready before returning PlannedNode, but it seems it causes delay and lock because image pull may take time.

**Comment by fboudra** [comment]
@clarsonneur which connection implementation type are you using? netty or jersey? if you change the type, does it make any difference?

**Comment by clarsonneur** [comment]
Hi @fboudra , I'm using default netty one. The jersey fails as far as I remember with UCP. I'll make another try to confirm.

**Comment by KostyaSha** [comment]
Jersey shouldn't fail with UCP. UCP issue is in multiple keys instead of one key.

**Comment by clarsonneur** [comment]
Well, the multiple keys was failing also with netty, and fixed thanks to your hint with netty. But yeah, I never tried it back with jersey.

**Comment by clarsonneur** [comment]
I just did the test and I confirm your point @KostyaSha about keys. jersey or netty works great.

Now related to the overprovisionning concern, netty or jersey has globally the same behavior. Over provisionning...

**Comment by clarsonneur** [comment]
here is one simple start job with jersey:

2 slaves were started for a single request.

I'm wondering if the exception reported has influence or not...

```
nov. 22, 2016 9:49:57 AM com.github.kostyasha.yad.DockerCloud provision
INFOS: Asked to provision load: '1', for: 'docker' label
nov. 22, 2016 9:49:57 AM com.github.kostyasha.yad.DockerCloud provision
INFOS: Will provision 'hub.docker.corp.net/clarsonneur/jenkins-slave-base:0.1', for label: 'docker', in cloud: 'docker'
nov. 22, 2016 9:50:00 AM com.github.kostyasha.yad.DockerCloud addProvisionedSlave
INFOS: Provisioning 'hub.docker.corp.net/clarsonneur/jenkins-slave-base:0.1' number '0' on 'docker'; Total containers: '0'
nov. 22, 2016 9:50:01 AM com.github.kostyasha.yad.DockerCloud provisionWithWait
INFOS: Trying to run container for hub.docker.corp.net/clarsonneur/jenkins-slave-base:0.1
nov. 22, 2016 9:50:07 AM com.github.kostyasha.yad.DockerCloud provision
INFOS: Asked to provision load: '1', for: 'docker' label
nov. 22, 2016 9:50:07 AM com.github.kostyasha.yad.DockerCloud provision
INFOS: Will provision 'hub.docker.corp.net/clarsonneur/jenkins-slave-base:0.1', for label: 'docker', in cloud: 'docker'
nov. 22, 2016 9:50:09 AM com.github.kostyasha.yad.DockerCloud addProvisionedSlave
INFOS: Provisioning 'hub.docker.corp.net/clarsonneur/jenkins-slave-base:0.1' number '1' on 'docker'; Total containers: '1'
nov. 22, 2016 9:50:11 AM com.github.kostyasha.yad.DockerCloud provisionWithWait
INFOS: Trying to run container for hub.docker.corp.net/clarsonneur/jenkins-slave-base:0.1
nov. 22, 2016 9:50:17 AM hudson.slaves.NodeProvisioner$2 run
INFOS: hub.docker.corp.net/clarsonneur/jenkins-slave-base:0.1 provisioning successfully completed. We have now 2 computer(s)
nov. 22, 2016 9:50:17 AM hudson.slaves.NodeProvisioner$2 run
INFOS: hub.docker.corp.net/clarsonneur/jenkins-slave-base:0.1 provisioning successfully completed. We have now 3 computer(s)
nov. 22, 2016 9:50:18 AM com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher launch
INFOS: Starting connection command for 39351638fcb5506e35af4550906a142dc5a8df22e593470b978199476685d02d
nov. 22, 2016 9:50:18 AM com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher launch
INFOS: Starting connection command for ea1c9c3cfa58634996591764c479763b8874ff9fae32703fb354e2da34a6536d
nov. 22, 2016 9:50:19 AM com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher launch
INFOS: Successfully executed jnlp connection for '39351638fcb5506e35af4550906a142dc5a8df22e593470b978199476685d02d'
nov. 22, 2016 9:50:19 AM com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher launch
INFOS: Successfully executed jnlp connection for 'ea1c9c3cfa58634996591764c479763b8874ff9fae32703fb354e2da34a6536d'
nov. 22, 2016 9:50:22 AM hudson.TcpSlaveAgentListener$ConnectionHandler run
INFOS: Accepted connection #3 from /16.85.1.92:59690
nov. 22, 2016 9:50:22 AM hudson.TcpSlaveAgentListener$ConnectionHandler run
INFOS: Accepted connection #4 from /16.85.1.92:43870
nov. 22, 2016 9:50:27 AM com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher launch
INFOS: Launched slave '2.53.2' 'docker-ea1c9c3cfa58' based on 'ea1c9c3cfa58634996591764c479763b8874ff9fae32703fb354e2da34a6536d'
nov. 22, 2016 9:50:29 AM com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher launch
INFOS: Launched slave '2.53.2' 'docker-39351638fcb5' based on '39351638fcb5506e35af4550906a142dc5a8df22e593470b978199476685d02d'
nov. 22, 2016 9:50:40 AM hudson.tasks.Shell$DescriptorImpl getShellOrDefault
AVERTISSEMENT: null
java.io.IOException: Remote call on docker-ea1c9c3cfa58 failed
	at hudson.remoting.Channel.call(Channel.java:789)
	at hudson.tasks.Shell$DescriptorImpl.getShellOrDefault(Shell.java:141)
	at hudson.tasks.Shell.buildCommandLine(Shell.java:85)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:97)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Caused by: java.lang.NoClassDefFoundError: javax/servlet/ServletException
	at hudson.tasks.Shell$DescriptorImpl$Shellinterpreter.call(Shell.java:182)
	at hudson.tasks.Shell$DescriptorImpl$Shellinterpreter.call(Shell.java:177)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at hudson.remoting.Engine$1$1.run(Engine.java:62)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to docker-ea1c9c3cfa58(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
	at hudson.remoting.Channel.call(Channel.java:781)
	... 13 more
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletException
	at hudson.remoting.RemoteClassLoader$ClassLoaderProxy.fetch(RemoteClassLoader.java:724)
	at sun.reflect.GeneratedMethodAccessor128.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:608)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at org.jenkinsci.remoting.CallableDecorator.call(CallableDecorator.java:18)
	at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to channel(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.Request.call(Request.java:172)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:253)
	at com.sun.proxy.$Proxy6.fetch(Unknown Source)
	at hudson.remoting.RemoteClassLoader.findClass(RemoteClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at hudson.tasks.Shell$DescriptorImpl$Shellinterpreter.call(Shell.java:182)
	at hudson.tasks.Shell$DescriptorImpl$Shellinterpreter.call(Shell.java:177)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at hudson.remoting.Engine$1$1.run(Engine.java:62)
	at java.lang.Thread.run(Thread.java:745)
nov. 22, 2016 9:51:18 AM hudson.model.Run execute
INFOS: test #3 main build action completed: SUCCESS
nov. 22, 2016 9:51:18 AM com.github.kostyasha.yad.DockerSlave _terminate
INFOS: Requesting disconnect for computer: 'docker-ea1c9c3cfa58'
```

**Comment by clarsonneur** [comment]
I found something that seems to provide the appropriate behavior to me. Does it make sense to you guys? or my proposal is quite too simple... :smile:

**Comment by clarsonneur** [comment]
I just tested the code I submitted in #115 with my stress test (10 jobs started in parallel) and it works great... so, it looks like I fixed the issue, but I'd like to have expert feedback, guys! :smiley:

**Comment by KostyaSha** [comment]
For ssh slaves it has timeout, jnlp afair also had timeout. So for such behaviours i made cleanups...

**Comment by clarsonneur** [comment]
@KostyaSha just for my knowledge: When does the plugins gets published to jenkins repository? Do we have a delay to get it from this official central jenkins place?

**Comment by KostyaSha** [comment]
It under jucies and via jucies it releases ASAP, in jenkins center with delay. I can run release now if you want.

**Comment by clarsonneur** [comment]
No, I guess it is ok. I just wanted to get news when available. thank you.

**Comment by KostyaSha** [comment]
@clarsonneur i mean kick me for release, ok released.

**Comment by clarsonneur** [comment]
Great! Thank you!
