### ISSUE TITLE
Problem connecting to Docker Container after creation

### ISSUE THREAD

**Issue by kunzsoni** [KostyaSha/yet-another-docker-plugin#121]
```
WARNING: Can't connect to ssh for localhost:32771
java.io.IOException: There was a problem while connecting to localhost:32771
        at com.trilead.ssh2.Connection.connect(Connection.java:818)
        at com.github.kostyasha.yad.utils.HostAndPortChecker.bySshWithEveryRetryWaitFor(HostAndPortChecker.java:89)
        at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:90)
        at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:219)
        at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:120)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
        at com.trilead.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:93)
        at com.trilead.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:230)
        at com.trilead.ssh2.Connection.connect(Connection.java:770)
        ... 9 more
Caused by: java.io.IOException: Cannot read full block, EOF reached.
        at com.trilead.ssh2.crypto.cipher.CipherInputStream.getBlock(CipherInputStream.java:81)
        at com.trilead.ssh2.crypto.cipher.CipherInputStream.read(CipherInputStream.java:108)
        at com.trilead.ssh2.transport.TransportConnection.receiveMessage(TransportConnection.java:232)
        at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:693)
        at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:489)
        ... 1 more

Jan 08, 2017 10:58:37 AM com.github.kostyasha.yad.DockerCloud provisionWithWait
SEVERE: Container 5bc1f5aee4e58b591cdbdb0fb77a5e6cd9419c7bbf9a9545a0ae179f0452e442 is not ready for ssh slave connection.
Jan 08, 2017 10:58:37 AM com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher getSSHLauncher
INFO: Creating slave SSH launcher for 'localhost:32772'. Cloud: 'dockerCloud'. Template: 'dockerslave'
Jan 08, 2017 10:58:44 AM hudson.
```

**Comment by kunzsoni** [comment]
could someone please help me with this. I am not sure why port 32772 is being tried to contact. I am using this plugin for jenkins on tomcat. opensuse is the base OS both for master machine and the docker slave. the container is created but cannot be contacted.

**Comment by kunzsoni** [comment]
@KostyaSha could you please suggest something here.

**Comment by KostyaSha** [comment]
Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
Try pick logs on container ssh side

**Comment by KostyaSha** [comment]
> could someone please help me with this. I am not sure why port 32772 is being tried to contact.

Maybe you have docker daemon on the `localhost` as jenkins master?
