### ISSUE TITLE
Deadlock with several jobs

### ISSUE THREAD

**Issue by gschrader** [KostyaSha/yet-another-docker-plugin#128]
I end up with slaves that have jobs that have completed but that haven't terminated completely. It doesn't seem to happen all the time but seems to occur fairly regularly as well. Similar to what is reported in [JENKINS-31536](https://issues.jenkins-ci.org/browse/JENKINS-31536) though it looks to be a different issue.

I performed a heap dump and I think the deadlock is with the synchronized method `com.github.kostyasha.yad.DockerCloud#getClient`. 

The 2 threads in question are:
```
jenkins.util.Timer [#8]

"jenkins.util.Timer [#8]" Id=31 Group=main WAITING on java.util.concurrent.CountDownLatch$Sync@20073d3b
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.CountDownLatch$Sync@20073d3b
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:92)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.netty.InvocationBuilder$ResponseCallback.awaitResult(InvocationBuilder.java:60)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.netty.InvocationBuilder.get(InvocationBuilder.java:189)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.netty.exec.ListContainersCmdExec.execute(ListContainersCmdExec.java:47)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.netty.exec.ListContainersCmdExec.execute(ListContainersCmdExec.java:18)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.netty.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.kostyasha.yad.DockerCloud.countCurrentDockerSlaves(DockerCloud.java:247)
	at com.github.kostyasha.yad.DockerCloud.addProvisionedSlave(DockerCloud.java:274)
	-  locked com.github.kostyasha.yad.DockerCloud@34fa2fe4
	at com.github.kostyasha.yad.DockerCloud.provision(DockerCloud.java:108)
	-  locked com.github.kostyasha.yad.DockerCloud@34fa2fe4
	at com.github.kostyasha.yad.DockerProvisioningStrategy.apply(DockerProvisioningStrategy.java:78)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:307)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:60)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:798)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

	Number of locked synchronizers = 2
	- java.util.concurrent.ThreadPoolExecutor$Worker@437a2251
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@2a1c722
```
and
```
Computer.threadPoolForRemoting [#667]

"Computer.threadPoolForRemoting [#667]" Id=9766 Group=main BLOCKED on com.github.kostyasha.yad.DockerCloud@34fa2fe4 owned by "jenkins.util.Timer [#8]" Id=31
	at com.github.kostyasha.yad.DockerCloud.getClient(DockerCloud.java:89)
	-  blocked on com.github.kostyasha.yad.DockerCloud@34fa2fe4
	at com.github.kostyasha.yad.DockerSlave.getClient(DockerSlave.java:196)
	at com.github.kostyasha.yad.DockerSlave._terminate(DockerSlave.java:155)
	at hudson.slaves.AbstractCloudSlave.terminate(AbstractCloudSlave.java:67)
	at com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy.lambda$null$0(DockerOnceRetentionStrategy.java:127)
	at com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy$$Lambda$25/1650996249.run(Unknown Source)
	at hudson.model.Queue._withLock(Queue.java:1309)
	at hudson.model.Queue.withLock(Queue.java:1186)
	at com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy.lambda$done$1(DockerOnceRetentionStrategy.java:123)
	at com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy$$Lambda$24/1200302130.run(Unknown Source)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

	Number of locked synchronizers = 2
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@2680d4b4
	- java.util.concurrent.ThreadPoolExecutor$Worker@ebb76ac
```

So it looks like it's hanging while it is trying to provision a new slave while terminating another. Any ideas what could be wrong here?

Here is my cloud section from `config.xml`:
```
<clouds>
   <com.github.kostyasha.yad.DockerCloud plugin="yet-another-docker-plugin@0.1.0-SNAPSHOT">
     <name>dockerhost</name>
     <provisionedImages>
       <entry>
         <com.github.kostyasha.yad.DockerSlaveTemplate>
           <id>84bc0f94-cff7-4b78-81ae-c04bc7073a50</id>
           <labelString>docker foo</labelString>
           <launcher class="com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher">
             <launchTimeout>120</launchTimeout>
             <user>jenkins</user>
             <jvmOpts></jvmOpts>
             <slaveOpts></slaveOpts>
             <jenkinsUrl>http://jenkins:8080</jenkinsUrl>
             <noCertificateCheck>false</noCertificateCheck>
           </launcher>
           <remoteFs>/home/jenkins</remoteFs>
           <maxCapacity>10</maxCapacity>
           <mode>NORMAL</mode>
           <retentionStrategy class="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">
             <idleMinutes>10</idleMinutes>
             <idleMinutes defined-in="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">10</idleMinutes>
           </retentionStrategy>
           <numExecutors>1</numExecutors>
           <dockerContainerLifecycle>
             <image>jenkins-slave:1.0.0</image>
             <pullImage>
               <pullStrategy>PULL_LATEST</pullStrategy>
               <credentialsId></credentialsId>
             </pullImage>
             <createContainer>
               <command></command>
               <hostname></hostname>
               <dnsHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                 <c class="list"/>
                 <list reference="../c"/>
               </dnsHosts>
               <volumes class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                 <c class="list"/>
                 <list reference="../c"/>
               </volumes>
               <volumesFrom class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                 <c class="list"/>
                 <list reference="../c"/>
               </volumesFrom>
               <environment class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                 <c class="list"/>
                 <list reference="../c"/>
               </environment>
               <bindPorts></bindPorts>
               <bindAllPorts>false</bindAllPorts>
               <memoryLimit>0</memoryLimit>
               <privileged>false</privileged>
               <tty>false</tty>
               <extraHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                 <c class="list"/>
                 <list reference="../c"/>
               </extraHosts>
               <networkMode>jenkins-network</networkMode>
               <devices class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                 <c class="list"/>
                 <list reference="../c"/>
               </devices>
               <cpusetCpus></cpusetCpus>
               <cpusetMems></cpusetMems>
               <links class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                 <c class="list"/>
                 <list reference="../c"/>
               </links>
             </createContainer>
             <stopContainer>
               <timeout>10</timeout>
             </stopContainer>
             <removeContainer>
               <removeVolumes>true</removeVolumes>
               <force>false</force>
             </removeContainer>
           </dockerContainerLifecycle>
           <nodeProperties/>
         </com.github.kostyasha.yad.DockerSlaveTemplate>
         <int>0</int>
       </entry>
     </provisionedImages>
     <templates>
       <com.github.kostyasha.yad.DockerSlaveTemplate reference="../../provisionedImages/entry/com.github.kostyasha.yad.DockerSlaveTemplate"/>
     </templates>
     <containerCap>3</containerCap>
     <connector>
       <serverUrl>tcp://dockerhost:2376</serverUrl>
       <credentialsId>dockerhost</credentialsId>
       <connectorType>NETTY</connectorType>
     </connector>
   </com.github.kostyasha.yad.DockerCloud>
 </clouds>
```

**Comment by KostyaSha** [comment]
Maybe i saw something similar could you try Jersey instead NETTY?

**Comment by gschrader** [comment]
Sure I'll try Jersey, I'll report back tomorrow with the results as these jobs take a long time.

**Comment by KostyaSha** [comment]
I saw that some .await methods stuck for me in NETTY but i didn't investigate them because had no time to debug.

**Comment by KostyaSha** [comment]
Also the question is readTimeouts. They can't be small so it may make time to end waiting data or until tcp break.

**Comment by gschrader** [comment]
I haven't experienced and deadlocks using Jersey, thanks!

**Comment by KostyaSha** [comment]
@marcuslinke cc
