### ISSUE TITLE
NullPointer while provisioning

### ISSUE THREAD

**Issue by MansM** [KostyaSha/yet-another-docker-plugin#135]
yet-another-docker-plugin: 0.1.0-rc33
docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true

```
jenkins    | SEVERE: Error in provisioning; template='DockerSlaveTemplate[maxCapacity=25,id=buildslave-centos6,labelString=buildslave-centos6,launcher=com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher@47b99d1,remoteFs=/var/lib/jenkins,mode=EXCLUSIVE,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@14f2b81d[image=buildslave-centos6,pullImage=com.github.kostyasha.yad.commons.DockerPullImage@81f70d24,createContainer=<null>,stopContainer=com.github.kostyasha.yad.commons.DockerStopContainer@27f,removeContainer=com.github.kostyasha.yad.commons.DockerRemoveContainer@5b0f],nodeProperties=[]]' for cloud='manscloud'
jenkins    | java.lang.NullPointerException
jenkins    | 	at com.github.kostyasha.yad.DockerCloud.runContainer(DockerCloud.java:163)
jenkins    | 	at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:211)
jenkins    | 	at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:130)
jenkins    | 	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
jenkins    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jenkins    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
jenkins    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
jenkins    | 	at java.lang.Thread.run(Thread.java:745)
jenkins    |
jenkins    | Mar 12, 2017 5:14:59 PM hudson.slaves.NodeProvisioner$2 run
jenkins    | WARNING: Unexpected exception encountered while provisioning agent buildslave-centos6
jenkins    | java.lang.NullPointerException
jenkins    | 	at com.github.kostyasha.yad.DockerCloud.runContainer(DockerCloud.java:163)
jenkins    | 	at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:211)
jenkins    | 	at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:130)
jenkins    | 	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
jenkins    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jenkins    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
jenkins    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
jenkins    | 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by KostyaSha** [comment]
Please provide cloud config section from global config section

**Comment by MansM** [comment]
```
<clouds>
    <com.github.kostyasha.yad.DockerCloud plugin="yet-another-docker-plugin@0.1.0-rc33">
      <name>manscloud</name>
      <provisionedImages/>
      <templates>
        <com.github.kostyasha.yad.DockerSlaveTemplate>
  <id>aa35a978-7868-4ea5-b689-f8bdc0515b79</id>
  <labelString>buildslave-centos7</labelString>
  <launcher class="com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher">
    <sshConnector plugin="ssh-slaves@1.11">
      <port>22</port>
      <credentialsId>jenkins</credentialsId>
      <jvmOptions></jvmOptions>
      <javaPath></javaPath>
      <maxNumRetries>0</maxNumRetries>
      <retryWaitTime>0</retryWaitTime>
    </sshConnector>
  </launcher>
  <remoteFs>/var/lib/jenkins</remoteFs>
  <maxCapacity>25</maxCapacity>
  <mode>EXCLUSIVE</mode>
  <retentionStrategy class="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">
    <idleMinutes>10</idleMinutes>
    <idleMinutes defined-in="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">10</idleMinutes>
  </retentionStrategy>
  <numExecutors>1</numExecutors>
  <dockerContainerLifecycle>
    <image>buildslave-centos7</image>
    <pullImage>
      <pullStrategy>PULL_NEVER</pullStrategy>
      <credentialsId></credentialsId>
    </pullImage>
    <createContainer>
      <command></command>
      <hostname></hostname>
      <dnsHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
        <c class="list"/>
        <list reference="../c"/>
      </dnsHosts>
      <volumes class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
        <c class="list">
          <string>/var/lib/jenkins:/var/lib/jenkins</string>
        </c>
        <list reference="../c"/>
      </volumes>
      <volumesFrom class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
        <c class="list"/>
        <list reference="../c"/>
      </volumesFrom>
      <environment class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
        <c class="list"/>
        <list reference="../c"/>
      </environment>
      <bindPorts></bindPorts>
      <bindAllPorts>true</bindAllPorts>
      <memoryLimit>2000</memoryLimit>
      <privileged>false</privileged>
      <tty>false</tty>
      <extraHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
        <c class="list"/>
        <list reference="../c"/>
      </extraHosts>
      <devices class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
        <c class="list"/>
        <list reference="../c"/>
      </devices>
      <cpusetCpus></cpusetCpus>
      <cpusetMems></cpusetMems>
    </createContainer>
    <stopContainer>
      <timeout>10</timeout>
    </stopContainer>
    <removeContainer>
      <removeVolumes>false</removeVolumes>
      <force>false</force>
    </removeContainer>
  </dockerContainerLifecycle>
  <nodeProperties/>
</com.github.kostyasha.yad.DockerSlaveTemplate>
        <com.github.kostyasha.yad.DockerSlaveTemplate>
  <id>buildslave-centos6</id>
  <labelString>buildslave-centos6</labelString>
  <launcher class="com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher">
    <sshConnector plugin="ssh-slaves@1.11">
      <port>22</port>
      <credentialsId>jenkins</credentialsId>
      <jvmOptions></jvmOptions>
      <javaPath></javaPath>
      <maxNumRetries>0</maxNumRetries>
      <retryWaitTime>0</retryWaitTime>
    </sshConnector>
  </launcher>
  <remoteFs>/var/lib/jenkins</remoteFs>
  <maxCapacity>25</maxCapacity>
  <mode>EXCLUSIVE</mode>
  <numExecutors>1</numExecutors>
  <dockerContainerLifecycle>
    <image>buildslave-centos6</image>
    <pullImage>
      <pullStrategy>PULL_NEVER</pullStrategy>
      <credentialsId></credentialsId>
    </pullImage>
    <stopContainer>
      <timeout>10</timeout>
    </stopContainer>
    <removeContainer>
      <removeVolumes>false</removeVolumes>
      <force>false</force>
    </removeContainer>
  </dockerContainerLifecycle>
  <nodeProperties/>
</com.github.kostyasha.yad.DockerSlaveTemplate>
      </templates>
      <containerCap>50</containerCap>
      <connector>
        <serverUrl>unix:///var/run/docker.sock</serverUrl>
        <credentialsId></credentialsId>
        <connectorType>JERSEY</connectorType>
      </connector>
    </com.github.kostyasha.yad.DockerCloud>
  </clouds>
```

**Comment by KostyaSha** [comment]
Second slave configuration is broken, it missing createContainer while first is right. Try save again...

**Comment by MansM** [comment]
didnt solve it:

```
jenkins    | Mar 16, 2017 1:01:48 PM com.github.kostyasha.yad.DockerCloud lambda$provision$0
jenkins    | SEVERE: Error in provisioning; template='DockerSlaveTemplate[maxCapacity=25,id=buildslave-centos6,labelString=buildslave-centos6,launcher=com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher@e5efd19,remoteFs=/var/lib/jenkins,mode=EXCLUSIVE,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@10e9942c[image=buildslave-centos6,pullImage=com.github.kostyasha.yad.commons.DockerPullImage@44aff73f,createContainer=DockerCreateContainer[command=,hostname=,dnsHosts=[],volumes=[/var/lib/jenkins:/var/lib/jenkins],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=true,memoryLimit=2000,cpuShares=<null>,privileged=false,tty=false,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=,links=[]],stopContainer=com.github.kostyasha.yad.commons.DockerStopContainer@27f,removeContainer=com.github.kostyasha.yad.commons.DockerRemoveContainer@5b0f],nodeProperties=[]]' for cloud='manscloud'
jenkins    | java.lang.NullPointerException
jenkins    | 	at com.github.kostyasha.yad_docker_java.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
jenkins    | 	at com.github.kostyasha.yad_docker_java.com.google.common.net.HostAndPort.fromString(HostAndPort.java:168)
jenkins    | 	at com.github.kostyasha.yad_docker_java.com.google.common.net.HostAndPort.fromParts(HostAndPort.java:135)
jenkins    | 	at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.getHostAndPort(DockerComputerSSHLauncher.java:153)
jenkins    | 	at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:85)
jenkins    | 	at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:233)
jenkins    | 	at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:130)
jenkins    | 	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
jenkins    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jenkins    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
jenkins    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
jenkins    | 	at java.lang.Thread.run(Thread.java:745)
jenkins    |
jenkins    | Mar 16, 2017 1:01:57 PM hudson.slaves.NodeProvisioner$2 run
jenkins    | WARNING: Unexpected exception encountered while provisioning agent buildslave-centos6
jenkins    | java.lang.NullPointerException
jenkins    | 	at com.github.kostyasha.yad_docker_java.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
jenkins    | 	at com.github.kostyasha.yad_docker_java.com.google.common.net.HostAndPort.fromString(HostAndPort.java:168)
jenkins    | 	at com.github.kostyasha.yad_docker_java.com.google.common.net.HostAndPort.fromParts(HostAndPort.java:135)
jenkins    | 	at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.getHostAndPort(DockerComputerSSHLauncher.java:153)
jenkins    | 	at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:85)
jenkins    | 	at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:233)
jenkins    | 	at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:130)
jenkins    | 	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
jenkins    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jenkins    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
jenkins    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
jenkins    | 	at java.lang.Thread.run(Thread.java:745)
jenkins    |
jenkins    | Mar 16, 2017 1:01:57 PM com.github.kostyasha.yad.DockerCloud provision
jenkins    | INFO: Asked to provision load: '1', for: 'buildslave-centos6' label
jenkins    | Mar 16, 2017 1:01:57 PM com.github.kostyasha.yad.DockerCloud provision
jenkins    | INFO: Will provision 'buildslave-centos6', for label: 'buildslave-centos6', in cloud: 'manscloud'
jenkins    | Mar 16, 2017 1:01:57 PM com.github.kostyasha.yad.DockerCloud addProvisionedSlave
jenkins    | INFO: Provisioning 'buildslave-centos6' number '9' on 'manscloud'; Total containers: '9'
jenkins    | Mar 16, 2017 1:01:58 PM com.github.kostyasha.yad.DockerCloud provisionWithWait
jenkins    | INFO: Trying to run container for buildslave-centos6
jenkins    | Mar 16, 2017 1:01:58 PM com.github.kostyasha.yad.DockerCloud lambda$provision$0
```

```
<clouds>
    <com.github.kostyasha.yad.DockerCloud plugin="yet-another-docker-plugin@0.1.0-rc33">
      <name>manscloud</name>
      <provisionedImages/>
      <templates>
        <com.github.kostyasha.yad.DockerSlaveTemplate>
          <id>aa35a978-7868-4ea5-b689-f8bdc0515b79</id>
          <labelString>buildslave-centos7</labelString>
          <launcher class="com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher">
            <sshConnector plugin="ssh-slaves@1.13">
              <port>22</port>
              <credentialsId>jenkins</credentialsId>
              <jvmOptions></jvmOptions>
              <javaPath></javaPath>
              <maxNumRetries>0</maxNumRetries>
              <retryWaitTime>0</retryWaitTime>
            </sshConnector>
          </launcher>
          <remoteFs>/var/lib/jenkins</remoteFs>
          <mode>EXCLUSIVE</mode>
          <retentionStrategy class="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">
            <idleMinutes>10</idleMinutes>
            <idleMinutes defined-in="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">10</idleMinutes>
          </retentionStrategy>
          <numExecutors>1</numExecutors>
          <dockerContainerLifecycle>
            <image>buildslave-centos7</image>
            <pullImage>
              <pullStrategy>PULL_NEVER</pullStrategy>
              <credentialsId></credentialsId>
            </pullImage>
            <createContainer>
              <command></command>
              <hostname></hostname>
              <dnsHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </dnsHosts>
              <volumes class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list">
                  <string>/var/lib/jenkins:/var/lib/jenkins</string>
                </c>
                <list reference="../c"/>
              </volumes>
              <volumesFrom class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </volumesFrom>
              <environment class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </environment>
              <bindPorts></bindPorts>
              <bindAllPorts>true</bindAllPorts>
              <memoryLimit>2000</memoryLimit>
              <privileged>false</privileged>
              <tty>false</tty>
              <extraHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </extraHosts>
              <devices class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </devices>
              <cpusetCpus></cpusetCpus>
              <cpusetMems></cpusetMems>
              <links class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </links>
            </createContainer>
            <stopContainer>
              <timeout>10</timeout>
            </stopContainer>
            <removeContainer>
              <removeVolumes>false</removeVolumes>
              <force>false</force>
            </removeContainer>
          </dockerContainerLifecycle>
          <nodeProperties/>
          <maxCapacity>25</maxCapacity>
        </com.github.kostyasha.yad.DockerSlaveTemplate>
        <com.github.kostyasha.yad.DockerSlaveTemplate>
          <id>buildslave-centos6</id>
          <labelString>buildslave-centos6</labelString>
          <launcher class="com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher">
            <sshConnector plugin="ssh-slaves@1.13">
              <port>22</port>
              <credentialsId>jenkins</credentialsId>
              <jvmOptions></jvmOptions>
              <javaPath></javaPath>
              <maxNumRetries>0</maxNumRetries>
              <retryWaitTime>0</retryWaitTime>
            </sshConnector>
          </launcher>
          <remoteFs>/var/lib/jenkins</remoteFs>
          <mode>EXCLUSIVE</mode>
          <retentionStrategy class="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">
            <idleMinutes>10</idleMinutes>
            <idleMinutes defined-in="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">10</idleMinutes>
          </retentionStrategy>
          <numExecutors>1</numExecutors>
          <dockerContainerLifecycle>
            <image>buildslave-centos6</image>
            <pullImage>
              <pullStrategy>PULL_NEVER</pullStrategy>
              <credentialsId></credentialsId>
            </pullImage>
            <createContainer>
              <command></command>
              <hostname></hostname>
              <dnsHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </dnsHosts>
              <volumes class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list">
                  <string>/var/lib/jenkins:/var/lib/jenkins</string>
                </c>
                <list reference="../c"/>
              </volumes>
              <volumesFrom class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </volumesFrom>
              <environment class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </environment>
              <bindPorts></bindPorts>
              <bindAllPorts>true</bindAllPorts>
              <memoryLimit>2000</memoryLimit>
              <privileged>false</privileged>
              <tty>false</tty>
              <extraHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </extraHosts>
              <devices class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </devices>
              <cpusetCpus></cpusetCpus>
              <cpusetMems></cpusetMems>
              <links class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </links>
            </createContainer>
            <stopContainer>
              <timeout>10</timeout>
            </stopContainer>
            <removeContainer>
              <removeVolumes>false</removeVolumes>
              <force>false</force>
            </removeContainer>
          </dockerContainerLifecycle>
          <nodeProperties/>
          <maxCapacity>25</maxCapacity>
        </com.github.kostyasha.yad.DockerSlaveTemplate>
      </templates>
      <containerCap>50</containerCap>
      <connector>
        <serverUrl>unix:///var/run/docker.sock</serverUrl>
        <credentialsId></credentialsId>
        <connectorType>JERSEY</connectorType>
      </connector>
    </com.github.kostyasha.yad.DockerCloud>
  </clouds>
```

**Comment by KostyaSha** [comment]
Could you revert to previous versions i.e. 31?

**Comment by MansM** [comment]
tried it.. didnt work either.

can you maybe provide me with a (at your side) working config with the following settings:
* serverurl = unix:///var/run/docker.sock
* 2 images/labels:
  * buildslave-centos6
  * buildslave-centos7

I will test it asap

**Comment by KostyaSha** [comment]
> serverurl = unix:///var/run/docker.sock

Never use socket connections from java, that unstable pain because require to package OS native libraries. 

So now i see createcontainer settings in config and it shouldn't raise NPE anymore.

**Comment by MansM** [comment]
with a bit of socat hacking I can go without the unix socket, but for some reason it doesnt request the ip by docker. it only wants to connect to the ip specified in the connection string (which of course doesnt work)

**Comment by MansM** [comment]
socat -d TCP-LISTEN:2376,fork UNIX:/var/run/docker.sock

**Comment by KostyaSha** [comment]
so did it help?

**Comment by KostyaSha** [comment]
No reply, closing... 🐌
