### ISSUE TITLE
Bug: fails to pull large docker images

### ISSUE THREAD

**Issue by samrocketman** [KostyaSha/yet-another-docker-plugin#143]
We use large docker base images with several development tools installed (e.g. an image which is capable of building several different languages).  The image size is larger than 4GB.  When using the `pull once and update latest` pull strategy the yet-another-docker-plugin fails to pull and throws errors in the logs.

```
Pulling image 'someregistry.example.com:5000/image:version' since one wasn't pulled before.. This may take awhile...

Apr 04, 2017 9:54:31 PM SEVERE com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.async.ResultCallbackTemplate onError

Error during callback
java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:171)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
    at sun.security.ssl.InputRecord.read(InputRecord.java:503)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
    at com.github.kostyasha.yad_docker_java.org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
    at com.github.kostyasha.yad_docker_java.org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
    at com.github.kostyasha.yad_docker_java.org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
    at com.github.kostyasha.yad_docker_java.org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:265)
    at com.github.kostyasha.yad_docker_java.org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:226)
    at com.github.kostyasha.yad_docker_java.org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:185)
    at com.github.kostyasha.yad_docker_java.org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:102)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.util.WrappedResponseInputStream.read(WrappedResponseInputStream.java:44)
    at com.github.kostyasha.yad_docker_java.com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
    at com.github.kostyasha.yad_docker_java.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2904)
    at com.github.kostyasha.yad_docker_java.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2899)
    at com.github.kostyasha.yad_docker_java.com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:692)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.async.JsonStreamProcessor.processResponseStream(JsonStreamProcessor.java:56)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:66)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Apr 04, 2017 9:54:31 PM SEVERE com.github.kostyasha.yad.DockerCloud lambda$provision$0

Error in provisioning; template='DockerSlaveTemplate[id=467747d5-7120-4bcc-bb19-5b86730798d5,labelString=many labels,launcher=com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher@2c82e0af,remoteFs=/srv/jenkins,maxCapacity=2,mode=EXCLUSIVE,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@13bb5d46[image=someregistry.example.com:5000/image:version,pullImage=com.github.kostyasha.yad.commons.DockerPullImage@dff2fc97,createContainer=DockerCreateContainer[command=/sbin/dumb-init /sbin/runsvdir -P /etc/service,hostname=,dnsHosts=[],volumes=[],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=false,memoryLimit=<null>,cpuShares=<null>,privileged=false,tty=false,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=,links=[]],stopContainer=com.github.kostyasha.yad.commons.DockerStopContainer@27f,removeContainer=com.github.kostyasha.yad.commons.DockerRemoveContainer@5b0f],nodeProperties=<null>]' for cloud='somecloud.example.com'
java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
    at com.github.kostyasha.yad_docker_java.com.google.common.base.Throwables.propagate(Throwables.java:160)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.async.ResultCallbackTemplate.getFirstError(ResultCallbackTemplate.java:133)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:94)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:41)
    at com.github.kostyasha.yad.commons.DockerPullImage.exec(DockerPullImage.java:111)
    at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:205)
    at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:128)
    at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:171)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
    at sun.security.ssl.InputRecord.read(InputRecord.java:503)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
    at com.github.kostyasha.yad_docker_java.org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
    at com.github.kostyasha.yad_docker_java.org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
    at com.github.kostyasha.yad_docker_java.org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
    at com.github.kostyasha.yad_docker_java.org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:265)
    at com.github.kostyasha.yad_docker_java.org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:226)
    at com.github.kostyasha.yad_docker_java.org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:185)
    at com.github.kostyasha.yad_docker_java.org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:102)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.util.WrappedResponseInputStream.read(WrappedResponseInputStream.java:44)
    at com.github.kostyasha.yad_docker_java.com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
    at com.github.kostyasha.yad_docker_java.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2904)
    at com.github.kostyasha.yad_docker_java.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2899)
    at com.github.kostyasha.yad_docker_java.com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:692)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.async.JsonStreamProcessor.processResponseStream(JsonStreamProcessor.java:56)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:66)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
    ... 4 more


```

The images don't get pulled down.  However, if I manually pull the images on the docker cloud then it works.

**Comment by KostyaSha** [comment]
Did you set anywhere readTimeouts?

**Comment by KostyaSha** [comment]
If you didn't set any readTimeouts and it unlimited, then you have communication errors between jenkins and docker daemon, especially nat or tcp timeouts.

**Comment by samrocketman** [comment]
I'll ger back to you on read timeouts.
