### ISSUE TITLE
unix:///var/run/docker.sock JNLP permission denied

### ISSUE THREAD

**Issue by jamroks** [KostyaSha/yet-another-docker-plugin#146]
Hi, 

 first of all thank you for the plugin . i haven't used it in prod CI environment yet , i was experimenting 
with it and it look promising . 1 month ago i was on version 0.31 and it was working well . Than yesterday i rebuild the lab environment with : 

- docker : 17.0.3-ce
- Docker version	API version
   1.13.1 & 17.03.0	1.26
- yad : 0.31
- connector type: jersey 
- jenkins in a docker container: 2.32.3 ( the same i was using one month ago)
the jenkins connaiter is launch with priviledge = true and binding of /var/run/docker.sock
I did setup the configuration to : unix:///var/run/docker.sock then click on test connection and i keep on getting the following error in the jenkins UI.

*******************************************************************
```
org.newsclub.net.unix.AFUNIXSocketException: Permission denied (socket: /run/docker.sock)
com.github.kostyasha.yad_docker_java.javax.ws.rs.ProcessingException: org.newsclub.net.unix.AFUNIXSocketException: Permission denied (socket: /run/docker.sock)
	at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
	at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
	at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:420)
	at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:316)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.VersionCmdExec.execute(VersionCmdExec.java:26)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.VersionCmdExec.execute(VersionCmdExec.java:13)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.kostyasha.yad.DockerConnector$DescriptorImpl.doTestConnection(DockerConnector.java:229)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:335)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:175)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:108)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:236)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
*******************************************************************
```

And when i look at the jenkins.log file i see this : 
*******************************************************************
Apr 10, 2017 8:59:07 PM com.github.kostyasha.yad_docker_java.org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
Apr 10, 2017 8:59:07 PM com.github.kostyasha.yad_docker_java.org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.newsclub.net.unix.AFUNIXSocketException) caught when processing request to {}->unix://localhost:80: Permission denied
Apr 10, 2017 8:59:07 PM com.github.kostyasha.yad_docker_java.org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
Apr 10, 2017 8:59:07 PM com.github.kostyasha.yad_docker_java.org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.newsclub.net.unix.AFUNIXSocketException) caught when processing request to {}->unix://localhost:80: Permission denied
Apr 10, 2017 8:59:07 PM com.github.kostyasha.yad_docker_java.org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
*******************************************************************

i'm not sure why the connection request is trying to bind to unix://localhost:80 
do you have any idea as to why this is hapenning ? 

PS: i tried to upgrade to version 0.34 of yet another plugin but with no luck, i get the exact same error
Thanks

**Comment by KostyaSha** [comment]
Never used socket connection. It source of pain because socket is os native while java is vm non-native language.
`socket: /run/docker.sock)` sounds like jenkins master has no permissions to new socket place?


> INFO: Retrying request to {}->unix://localhost:80

How much slashes did you set in UI?

**Comment by jamroks** [comment]
thanks for the reply , i used the below setting:

 unix:///var/run/docker.sock.
but yes i switched to ip based url for now. it's strange because in older version it used to work for me when setting unix socket.  but for now i can live with the ip/port based seeting 

thanks

**Comment by KostyaSha** [comment]
> but yes i switched to ip based url for now. it's strange because in older version it used to work for me when setting unix socket.

from my one night fighting - check that you have no selinux enabled on node :D
