### ISSUE TITLE
Cann't run container

### ISSUE THREAD

**Issue by xiaoxuetu** [KostyaSha/yet-another-docker-plugin#147]
```java
四月 13, 2017 7:18:54 下午 com.github.kostyasha.yad.DockerCloud provision
信息: Asked to provision load: '1', for: 'docker_test' label
四月 13, 2017 7:18:54 下午 com.github.kostyasha.yad.DockerCloud provision
信息: Will provision 'jenkinsci/jnlp-slave', for label: 'docker_test', in cloud: 'localhost'
四月 13, 2017 7:18:54 下午 com.github.kostyasha.yad.DockerCloud addProvisionedSlave
信息: Provisioning 'jenkinsci/jnlp-slave' number '0' on 'localhost'; Total containers: '0'
四月 13, 2017 7:18:54 下午 com.github.kostyasha.yad.DockerCloud provisionWithWait
信息: Trying to run container for jenkinsci/jnlp-slave
四月 13, 2017 7:19:04 下午 hudson.slaves.NodeProvisioner$2 run
信息: jenkinsci/jnlp-slave provisioning successfully completed. We have now 2 computer(s)
四月 13, 2017 7:19:04 下午 com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.async.ResultCallbackTemplate onError
严重: Error during callback
com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Container 4c07f0fd83fe065a8eb1ce95dcb6083ae422d109a420db7c3b31ec45fa050d7d is not running"}

	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:109)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at com.github.kostyasha.yad_docker_java.io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:233)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at com.github.kostyasha.yad_docker_java.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at com.github.kostyasha.yad_docker_java.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at com.github.kostyasha.yad_docker_java.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at com.github.kostyasha.yad_docker_java.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

四月 13, 2017 7:19:04 下午 com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher launch
严重: Can't execute jnlp connection command: '{"message":"Container 4c07f0fd83fe065a8eb1ce95dcb6083ae422d109a420db7c3b31ec45fa050d7d is not running"}'
四月 13, 2017 7:19:04 下午 com.github.kostyasha.yad.DockerSlave _terminate
信息: Requesting disconnect for computer: 'localhost-4c07f0fd83fe'
四月 13, 2017 7:19:04 下午 com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.async.ResultCallbackTemplate onError
严重: Error during callback
com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.exception.NotModifiedException: 
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:97)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at com.github.kostyasha.yad_docker_java.io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:233)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at com.github.kostyasha.yad_docker_java.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at com.github.kostyasha.yad_docker_java.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at com.github.kostyasha.yad_docker_java.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at com.github.kostyasha.yad_docker_java.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at com.github.kostyasha.yad_docker_java.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

四月 13, 2017 7:19:04 下午 com.github.kostyasha.yad.DockerSlave _terminate
信息: Container '4c07f0fd83fe065a8eb1ce95dcb6083ae422d109a420db7c3b31ec45fa050d7d' is already stopped.
四月 13, 2017 7:19:04 下午 com.github.kostyasha.yad.DockerSlave _terminate
信息: Removed container 4c07f0fd83fe065a8eb1ce95dcb6083ae422d109a420db7c3b31ec45fa050d7d
四月 13, 2017 7:19:14 下午 com.github.kostyasha.yad.DockerCloud provision
```

**Comment by KostyaSha** [comment]
> 信息: Trying to run container for jenkinsci/jnlp-slave
> 四月 13, 2017 7:19:04 下午 hudson.slaves.NodeProvisioner$2 run
> 信息: jenkinsci/jnlp-slave provisioning successfully completed. We have now 2 computer(s)
> 四月 13, 2017 7:19:04 下午 com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.async.ResultCallbackTemplate onError
> 严重: Error during callback
> com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Container 4c07f0fd83fe065a8eb1ce95dcb6083ae422d109a420db7c3b31ec45fa050d7d is not running"}

Never tried to use this container, please try  `java:8-jdk-alpine` firstly (covered in tests)

**Comment by xiaoxuetu** [comment]
I run the container sucessful, but failre when I use this plugin, alwarys throw the error

**Comment by KostyaSha** [comment]
So does `java:8-jdk-alpine` works without issues?

**Comment by xiaoxuetu** [comment]
When I use  `java:8-jdk-alpine` , the plugin can run a container and finish the build. when i use jenkinsci/jnlp-slave , i throw the error which metion above

**Comment by xiaoxuetu** [comment]
# Docker Version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false

# Jenkins Version 
Jenkins ver. 2.19.4
yet-another-docker-plugin@0.1.0-rc35

# Config about cloud setting and job
see the attachment 
[cloud config.xml.zip](https://github.com/KostyaSha/yet-another-docker-plugin/files/925636/config.xml.zip)

[job config - docker_slave_test_config.xml.zip](https://github.com/KostyaSha/yet-another-docker-plugin/files/925640/docker_slave_test_config.xml.zip)

**Comment by KostyaSha** [comment]
> When I use java:8-jdk-alpine , the plugin can run a container and finish the build.
> 
> When i use jenkinsci/jnlp-slave , it always throw the error which metion above except running it manually

My universal launcher may not work in all containers. You need check `docker logs -f $ID` on this container during launch attempt and you will see why it fails.

**Comment by KostyaSha** [comment]
Ok, found. Replacing docker `cmd` with `entrypoint` to bypass default entrypoint that obviously has other arguments expecting.
