### ISSUE TITLE
ClosedChannelException at the end of build job

### ISSUE THREAD

**Issue by vasya10** [KostyaSha/yet-another-docker-plugin#170]
Thanks for this plugin!

I have a successful execution of jenkinsfile declarative pipeline executing YADP instance. Jenkins is running as a docker container; A multibranch pipeline job creates an artifact and pushes docker image into Artifactory. However after the image is built and pushed successfully to registry, I see in the logs (docker logs -f $containerId) an exception (see below), that makes Jenkins think the build failed. Any thoughts would help!

Jenkins: 2.46.3 (from the hub.docker)
YADP uses Netty, JNLP Launcher, most values are default.
```
com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.model.Version@5d22f7dc[
  apiVersion=1.27
  arch=amd64
  gitCommit=c6d412e
  goVersion=go1.7.5
  kernelVersion=3.13.0-117-generic
  operatingSystem=linux
  version=17.03.1-ce
  buildTime=2017-03-27T17:10:36.401799458+00:00
  experimental=<null>
]
```

```
Jun 19, 2017 8:56:25 PM com.github.kostyasha.yad.DockerSlave _terminate
INFO: Requesting disconnect for computer: 'docker-jenkins-yadp-01-baf43f0a9f53'
Jun 19, 2017 8:56:25 PM jenkins.slaves.DefaultJnlpSlaveReceiver channelClosed
WARNING: Computer.threadPoolForRemoting [#20] for docker-jenkins-yadp-01-baf43f0a9f53 terminated
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:208)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:800)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:311)
	at hudson.remoting.Channel.close(Channel.java:1295)
	at hudson.remoting.Channel.close(Channel.java:1263)
	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:704)
	at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:96)
	at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:626)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Jun 19, 2017 8:56:25 PM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: grk-core-ux/GRK-392 #28 completed: FAILURE
```

**Comment by vasya10** [comment]
Actually I just realized this is not a YADP issue but with Jenkins Slave. YADP seems to have terminated normally. I will leave it open for now, but close if i find a solution.

**Comment by KostyaSha** [comment]
That's warning, ignore it. It doesn't affect anything.

**Comment by vasya10** [comment]
@KostyaSha thank you. Yes confirming that this is not an issue with YADP. For those who may stumble into similar situation - the issue was a previous line in the pipeline script. I was executing archiveArtifacts, but the file patterns were not found, which led to this error. Unfortunately Jenkins logs didn't tell me much, which led to believe container wasnt terminating. Thanks again!

**Comment by brandon-fryslie** [comment]
Does anyone know what the proper way to fix this is in the plugin?  Is there a way to properly handle this exception?  I would like to be able to keep my logs clean so real errors are more obvious.

**Comment by KostyaSha** [comment]
i have some WIP changes related on termination process, may influence...
