### ISSUE TITLE
Error in provisioning

### ISSUE THREAD

**Issue by nbars** [KostyaSha/yet-another-docker-plugin#174]
Hi,

I'am facing the same issue as #107 I think. I'am using docker with unix domain socket
and the slave is connected through SSH.

@KostyaSha you have recommended  several times to use JNLP, can you guide me to a location where it is explained how to use JNLP?

Please tell me if you need any further information. 

```
Jenkins version - 2.60.1
yet-another-docker-plugin version - 0.1.0-rc37	
```

```
Error in provisioning; template='DockerSlaveTemplate[maxCapacity=1,id=a5d933a4-bafe-4659-9419-df19f3280f68,labelString=arch-jenkins-slave-docker-privileged,launcher=com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher@45072cfc,remoteFs=/home/jenkins,mode=EXCLUSIVE,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@56f7e0eb[image=nbars/arch-jenkins-slave-docker,pullImage=com.github.kostyasha.yad.commons.DockerPullImage@d0728bec,createContainer=DockerCreateContainer[command=,hostname=,dnsHosts=[],volumes=[],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=false,memoryLimit=0,cpuShares=<null>,privileged=true,tty=false,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=,links=[]],stopContainer=com.github.kostyasha.yad.commons.DockerStopContainer@27f,removeContainer=com.github.kostyasha.yad.commons.DockerRemoveContainer@5b0f],nodeProperties=[]]' for cloud='docker'
java.lang.NullPointerException
  at com.github.kostyasha.yad_docker_java.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
  at com.github.kostyasha.yad_docker_java.com.google.common.net.HostAndPort.fromString(HostAndPort.java:168)
  at com.github.kostyasha.yad_docker_java.com.google.common.net.HostAndPort.fromParts(HostAndPort.java:135)
  at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.getHostAndPort(DockerComputerSSHLauncher.java:153)
  at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:85)
  at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:257)
  at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:134)
  at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:748)
```

```
jenkins@rootserver:~$ cat config.xml 
<?xml version='1.0' encoding='UTF-8'?>
<hudson>
  <disabledAdministrativeMonitors/>
  <version>2.60.1</version>
  <numExecutors>2</numExecutors>
  <mode>NORMAL</mode>
  <useSecurity>true</useSecurity>
  <authorizationStrategy class="hudson.security.ProjectMatrixAuthorizationStrategy">
    - snip -
  </authorizationStrategy>
  <securityRealm class="hudson.security.HudsonPrivateSecurityRealm">
    <disableSignup>true</disableSignup>
    <enableCaptcha>false</enableCaptcha>
  </securityRealm>
  <disableRememberMe>false</disableRememberMe>
  <projectNamingStrategy class="jenkins.model.ProjectNamingStrategy$DefaultProjectNamingStrategy"/>
  <workspaceDir>${JENKINS_HOME}/workspace/${ITEM_FULLNAME}</workspaceDir>
  <buildsDir>${ITEM_ROOTDIR}/builds</buildsDir>
  <markupFormatter class="hudson.markup.EscapedMarkupFormatter"/>
  <jdks/>
  <viewsTabBar class="hudson.views.DefaultViewsTabBar"/>
  <myViewsTabBar class="hudson.views.DefaultMyViewsTabBar"/>
  <clouds>
    <com.github.kostyasha.yad.DockerCloud plugin="yet-another-docker-plugin@0.1.0-rc37">
      <name>docker</name>
      <provisionedImages/>
      <templates>
        <com.github.kostyasha.yad.DockerSlaveTemplate>
          <id>a5d933a4-bafe-4659-9419-df19f3280f68</id>
          <labelString>arch-jenkins-slave-docker-privileged</labelString>
          <launcher class="com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher">
            <sshConnector plugin="ssh-slaves@1.20">
              <port>22</port>
              <credentialsId>bc72238b-852d-4ce2-915e-72a51d557d7a</credentialsId>
              <jvmOptions></jvmOptions>
              <javaPath></javaPath>
              <maxNumRetries>0</maxNumRetries>
              <retryWaitTime>0</retryWaitTime>
              <sshHostKeyVerificationStrategy class="hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy"/>
            </sshConnector>
          </launcher>
          <remoteFs>/home/jenkins</remoteFs>
          <mode>EXCLUSIVE</mode>
          <retentionStrategy class="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">
            <idleMinutes>10</idleMinutes>
            <idleMinutes defined-in="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">10</idleMinutes>
          </retentionStrategy>
          <numExecutors>1</numExecutors>
          <dockerContainerLifecycle>
            <image>nbars/arch-jenkins-slave-docker</image>
            <pullImage>
              <pullStrategy>PULL_LATEST</pullStrategy>
              <credentialsId></credentialsId>
            </pullImage>
            <createContainer>
              <command></command>
              <hostname></hostname>
              <dnsHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </dnsHosts>
              <volumes class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </volumes>
              <volumesFrom class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </volumesFrom>
              <environment class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </environment>
              <bindPorts></bindPorts>
              <bindAllPorts>false</bindAllPorts>
              <memoryLimit>0</memoryLimit>
              <privileged>true</privileged>
              <tty>false</tty>
              <extraHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </extraHosts>
              <devices class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </devices>
              <cpusetCpus></cpusetCpus>
              <cpusetMems></cpusetMems>
              <links class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </links>
            </createContainer>
            <stopContainer>
              <timeout>10</timeout>
            </stopContainer>
            <removeContainer>
              <removeVolumes>false</removeVolumes>
              <force>false</force>
            </removeContainer>
          </dockerContainerLifecycle>
          <nodeProperties/>
          <maxCapacity>1</maxCapacity>
        </com.github.kostyasha.yad.DockerSlaveTemplate>
      </templates>
      <containerCap>2</containerCap>
      <connector>
        <serverUrl>unix:///var/run/docker.sock</serverUrl>
        <credentialsId></credentialsId>
        <connectorType>JERSEY</connectorType>
      </connector>
    </com.github.kostyasha.yad.DockerCloud>
  </clouds>
  <quietPeriod>5</quietPeriod>
  <scmCheckoutRetryCount>0</scmCheckoutRetryCount>
  <views>
    <hudson.model.AllView>
      <owner class="hudson" reference="../../.."/>
      <name>all</name>
      <filterExecutors>false</filterExecutors>
      <filterQueue>false</filterQueue>
      <properties class="hudson.model.View$PropertyList"/>
    </hudson.model.AllView>
    <listView>
      <owner class="hudson" reference="../../.."/>
      <name>arch-asan</name>
      <filterExecutors>false</filterExecutors>
      <filterQueue>false</filterQueue>
      <properties class="hudson.model.View$PropertyList"/>
      <jobNames>
        <comparator class="hudson.util.CaseInsensitiveComparator"/>
      </jobNames>
      <jobFilters/>
      <columns>
        <hudson.views.StatusColumn/>
        <hudson.views.WeatherColumn/>
        <hudson.views.JobColumn/>
        <hudson.views.LastSuccessColumn/>
        <hudson.views.LastFailureColumn/>
        <hudson.views.LastDurationColumn/>
        <hudson.views.BuildButtonColumn/>
      </columns>
      <includeRegex>arch-asan.*</includeRegex>
      <recurse>false</recurse>
    </listView>
    <listView>
      <owner class="hudson" reference="../../.."/>
      <name>aur</name>
      <filterExecutors>false</filterExecutors>
      <filterQueue>false</filterQueue>
      <properties class="hudson.model.View$PropertyList"/>
      <jobNames>
        <comparator class="hudson.util.CaseInsensitiveComparator"/>
        <string>aur-cutecom</string>
        <string>aur-keepass-plugin-keechallenge</string>
      </jobNames>
      <jobFilters/>
      <columns>
        <hudson.views.StatusColumn/>
        <hudson.views.WeatherColumn/>
        <hudson.views.JobColumn/>
        <hudson.views.LastSuccessColumn/>
        <hudson.views.LastFailureColumn/>
        <hudson.views.LastDurationColumn/>
        <hudson.views.BuildButtonColumn/>
      </columns>
      <recurse>false</recurse>
    </listView>
    <listView>
      <owner class="hudson" reference="../../.."/>
      <name>aur-repo</name>
      <filterExecutors>false</filterExecutors>
      <filterQueue>false</filterQueue>
      <properties class="hudson.model.View$PropertyList"/>
      <jobNames>
        <comparator class="hudson.util.CaseInsensitiveComparator"/>
      </jobNames>
      <jobFilters/>
      <columns>
        <hudson.views.StatusColumn/>
        <hudson.views.WeatherColumn/>
        <hudson.views.JobColumn/>
        <hudson.views.LastSuccessColumn/>
        <hudson.views.LastFailureColumn/>
        <hudson.views.LastDurationColumn/>
        <hudson.views.BuildButtonColumn/>
      </columns>
      <includeRegex>aur-repo.*</includeRegex>
      <recurse>false</recurse>
    </listView>
  </views>
  <primaryView>all</primaryView>
  <slaveAgentPort>0</slaveAgentPort>
  <label></label>
  <nodeProperties/>
  <globalNodeProperties/>
```

**Comment by KostyaSha** [comment]
Even without looking at configs
```
at com.github.kostyasha.yad_docker_java.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
  at com.github.kostyasha.yad_docker_java.com.google.common.net.HostAndPort.fromString(HostAndPort.java:168)
 
```
You didn't specify or expose ssh port, so it not found and ssh launcher doesn't know where to connect to.

**Comment by KostyaSha** [comment]
For JNLP ensure that jenkins hostname is configured right and accessible from containers and just use sshlauncher.

**Comment by nbars** [comment]
The SSH port is expose. If I change the port in the plugin settings, I get the following error message:
```
Error in provisioning; template='DockerSlaveTemplate[maxCapacity=1,id=a5d933a4-bafe-4659-9419-df19f3280f68,labelString=arch-jenkins-slave-docker-privileged,launcher=com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher@529e6936,remoteFs=/home/jenkins,mode=EXCLUSIVE,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@2d5cdbf6[image=nbars/arch-jenkins-slave-docker,pullImage=com.github.kostyasha.yad.commons.DockerPullImage@d0728bec,createContainer=DockerCreateContainer[command=,hostname=,dnsHosts=[],volumes=[],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=false,memoryLimit=0,cpuShares=<null>,privileged=true,tty=false,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=,links=[]],stopContainer=com.github.kostyasha.yad.commons.DockerStopContainer@27f,removeContainer=com.github.kostyasha.yad.commons.DockerRemoveContainer@5b0f],nodeProperties=[]]' for cloud='docker'
java.lang.IllegalStateException: SSH Binding not found for 220caad4ad53236bfb86cf179e378d6ec40705119491d64991f2e9d1ef6b102b. Add EXPOSE in image or expose SSH port in container create configuration!
	at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.getHostAndPort(DockerComputerSSHLauncher.java:137)
	at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:85)
	at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:257)
	at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:134)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```
Thus, there must be some other reason for this error message.

**Comment by KostyaSha** [comment]
`          <launcher class="com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher">
            <sshConnector plugin="ssh-slaves@1.20">
              <port>22</port>
`
Do you have this port as `EXPOSE` in your docker image?

**Comment by KostyaSha** [comment]
Issues happens because you are using socket and SSHLauncher can't get host for daemon.
```
 <connector>
        <serverUrl>unix:///var/run/docker.sock</serverUrl>
        <credentialsId></credentialsId>
        <connectorType>JERSEY</connectorType>
      </connector>
```
I don't recommend using socket connection, also it means that you are running jenkins and docker on the same host that sounds not effective for production usage.
Simply expose REST API and use it...

**Comment by nbars** [comment]
Yes I do. I also checked if it is working by manually connecting to the container.
As a side note, the container stays alive although the plugin fails to connect.

**Comment by KostyaSha** [comment]
Seems socket protocol is valid, i guess SSHLauncher should do better check and through better error.

**Comment by nbars** [comment]
I can not find any good documentation for setting up JNLP, is there any place where it is described how to configure e.g. the secret?

**Comment by KostyaSha** [comment]
for jnlp you should have only valid jenkins hostname resolvable and accessible from container plus image should have java, shell. 
Try with `kostyasha/yet-another-docker-plugin:master`

**Comment by KostyaSha** [comment]
Btw, in case of unix protocol maybe sshlauncher should use jenkins address as host, WDYT? Maybe it will solve some % of cases when people trying to run on the same docker daemon.

**Comment by nbars** [comment]
I am trying to connect manually and get the following error
```
docker run  --rm jenkinsci/jnlp-slave -url https://domain.de secret test

java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Unknown client name: test
	at org.jenkinsci.remoting.util.SettableFuture.get(SettableFuture.java:223)
	at hudson.remoting.Engine.innerRun(Engine.java:385)
	at hudson.remoting.Engine.run(Engine.java:287)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Unknown client name: test
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.newAbortCause(ConnectionHeadersFilterLayer.java:375)
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.onRecvClosed(ConnectionHeadersFilterLayer.java:432)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:172)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$1500(BIONetworkLayer.java:48)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:247)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.nio.channels.ClosedChannelException
		... 7 more

```
How can allow a client to connect? Is there a 'chat application' for github, or how are you answering so fast?

**Comment by KostyaSha** [comment]
`> docker run  --rm jenkinsci/jnlp-slave -url https://domain.de secret test`
Sorry i don't know what do you do. If you want to use YADocker Cloud, then just try and look at errors. `jenkinsci/jnlp-slave` maybe will also work, but i can't guarantee. 
Just try and check system errors. 


> How can allow a client to connect? Is there a 'chat application' for github, or how are you answering so fast?

💤  need disable load email notification :(

**Comment by nbars** [comment]
Yeah, but if I want to use YADocker I need a suitable docker image right (like jenkinsci/jnlp-slave)? Which image should I use instead? Or I am on the wrong track?

**Comment by KostyaSha** [comment]
> Try with kostyasha/yet-another-docker-plugin:master

Then switch to any other, just to sure that you have working configuration.

**Comment by nbars** [comment]
Ah, I was confused because the image has the same name as you're project and I did not manage to pull it (because the tag is not master, kostyasha/yet-another-docker-plugin:wget-master it is).

However, now I have the following problem:
```
Will provision 'kostyasha/yet-another-docker-plugin:wget-master', for label: 'test-label', in cloud: 'docker'
Jul 03, 2017 12:41:50 AM INFORMATION com.github.kostyasha.yad.DockerCloud addProvisionedSlave
Provisioning 'kostyasha/yet-another-docker-plugin:wget-master' number '0' on 'docker'; Total containers: '0'
Jul 03, 2017 12:42:00 AM INFORMATION hudson.slaves.NodeProvisioner$2 run
kostyasha/yet-another-docker-plugin:wget-master provisioning successfully completed. We have now 2 computer(s)
Jul 03, 2017 12:42:00 AM INFORMATION com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher launch
Starting connection command for 567a07251e6a8b11e684c7cff7aee54593ba2c3f1986a81c17cdb67437d21f60
Jul 03, 2017 12:42:01 AM INFORMATION com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher launch
Successfully executed jnlp connection for '567a07251e6a8b11e684c7cff7aee54593ba2c3f1986a81c17cdb67437d21f60'
Jul 03, 2017 12:42:01 AM INFORMATION com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher launch
Launch timeout, termintaing slave based on '567a07251e6a8b11e684c7cff7aee54593ba2c3f1986a81c17cdb67437d21f60'
Jul 03, 2017 12:42:01 AM INFORMATION com.github.kostyasha.yad.DockerSlave _terminate
Requesting disconnect for computer: 'docker-567a07251e6a'
Jul 03, 2017 12:42:02 AM INFORMATION com.github.kostyasha.yad.DockerSlave _terminate
Stopped container 567a07251e6a8b11e684c7cff7aee54593ba2c3f1986a81c17cdb67437d21f60
Jul 03, 2017 12:42:02 AM INFORMATION com.github.kostyasha.yad.DockerSlave _terminate
Removed container 567a07251e6a8b11e684c7cff7aee54593ba2c3f1986a81c17cdb67437d21f60
Jul 03, 2017 12:42:10 AM INFORMATION com.github.kostyasha.yad.DockerCloud provision
Asked to provision load: '1', for: 'test-label' label
Jul 03, 2017 12:42:10 AM INFORMATION com.github.kostyasha.yad.DockerCloud provision
Will provision 'kostyasha/yet-another-docker-plugin:wget-master', for label: 'test-label', in cloud: 'docker'
Jul 03, 2017 12:42:10 AM INFORMATION com.github.kostyasha.yad.DockerCloud addProvisionedSlave
Provisioning 'kostyasha/yet-another-docker-plugin:wget-master' number '0' on 'docker'; Total containers: '0'

```
Also, in the project setting a warning is displayed: „Jenkins“ has not the label „test-label“).
Although I have configured the labels correct (and it is also suggested by the autocompletion of the labe field)

**Comment by KostyaSha** [comment]
Jenkins knows labels only for running slaves, it doesn't know that Cloud will add something. So ignore it.

**Comment by nbars** [comment]
Well, a fresh project also does not work...
Whats is about the ``Launch timeout, termintaing slave based on 'f029329d08c9b5689722d8636079ca72bca7009f963d1b205e10b40297302052'`` message?
Is there any further information I can acquire?

**Comment by KostyaSha** [comment]
read system log

**Comment by nbars** [comment]
This log posted above, is the system log. I will look into this tomorrow again. If you have any ideas I would really appreciate you're help. Thanks :-)

**Comment by KostyaSha** [comment]
Check `Cloud Stats` page in manage jenkins. Maybe it has attached error.

**Comment by nbars** [comment]
Nop, nothing there.

**Comment by nbars** [comment]
So, the problem was that the user name wasn't set. So, there might be something wrong with the default values?
```
++ JENKINS_URL=https://xxx.de/
++ JENKINS_USER=
++ JENKINS_HOME=/home/jenkins
++ COMPUTER_URL=computer/docker-04cd5a10dc7b/
++ COMPUTER_SECRET=secret
++ JAVA_OPTS=
++ SLAVE_OPTS=
++ NO_CERTIFICATE_CHECK=false
+ '[' -z https://xxxx.de/ ']'
+ '[' -z computer/docker-04cd5a10dc7b/ ']'
+ '[' -z /home/jenkins ']'
+ id -u ''
id: : no such user
+ echo 'Jenkins user doesn'\''t exist, creating...'
Jenkins user doesn't exist, creating...
++ command -v useradd
+ '[' -x /usr/sbin/useradd ']'
+ useradd -d /home/jenkins ''
useradd: invalid user name ''

```
It is working now, thanks!
