### ISSUE TITLE
Delayed SSH to the slave node 

### ISSUE THREAD

**Issue by imdurgadas** [KostyaSha/yet-another-docker-plugin#185]
I have setup a cloud along with the template. Cloud is setup to accept only those jobs that are matching the label.
During my execution , I see that even though the slave container is created, the plugin isn't able to SSH to it despite everything being up and running. (During the time of retries , i tried manually SSH'ng to the slave node and I could get in). However, it tries for 60 times and then throws a stacktrace. However . after this it gets connected and the jobs start executing on the node. 

Here are the logs so as to get idea about what is happening.

> 19-Aug-2017
 04:58:42.499 SEVERE [Computer.threadPoolForRemoting [#3]] com.github.kostyasha.yad.utils.HostAndPortChecker.bySshWithEveryRetryWaitFor Failed to connect to ecos0055:32768 (try 1/60) - The kexTimeout (2000 ms) expired.
........
........
19-Aug-2017 05:03:34.903 SEVERE [Computer.threadPoolForRemoting [#3]] com.github.kostyasha.yad.utils.HostAndPortChecker.bySshWithEveryRetryWaitFor Failed to connect to ecos0055:32768 (try 60/60) - The kexTimeout (2000 ms) expired.
19-Aug-2017 05:03:34.904 WARNING [Computer.threadPoolForRemoting [#3]] com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.waitUp Can't connect to ssh for ecos0055:32768
 java.net.SocketTimeoutException: The kexTimeout (2000 ms) expired.
        at com.trilead.ssh2.Connection.connect(Connection.java:827)
        at com.github.kostyasha.yad.utils.HostAndPortChecker.bySshWithEveryRetryWaitFor(HostAndPortChecker.java:89)
        at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:92)
        at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:257)
        at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:134)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)

> 19-Aug-2017
 05:03:34.905 SEVERE [Computer.threadPoolForRemoting [#3]] com.github.kostyasha.yad.DockerCloud.provisionWithWait Container b9e8394f94f30f61aad8fe19a625c143784c3e6c18592d0621f0b70d20c8e019 is not ready for ssh slave connection.
19-Aug-2017 05:03:34.906 INFO [Computer.threadPoolForRemoting [#3]] com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.getSSHLauncher Creating slave SSH launcher for 'ecos0055:32768'. Cloud: 'dc1'. Template: 'ecos0003:5000/jenkins_slave_ubuntu:16.04'
19-Aug-2017 05:03:44.151 INFO [jenkins.util.Timer [#9]] hudson.slaves.NodeProvisioner$2.run ecos0003:5000/jenkins_slave_ubuntu:16.04 provisioning successfully completed. We have now 2 computer(s)
19-Aug-2017 05:03:44.466 WARNING [SSHLauncher.launch for 'dc1-b9e8394f94f3' node [#1]] hudson.plugins.sshslaves.verifiers.TrileadVersionSupportManager.getTrileadSupport Could not create Trilead support class. Using legacy Trilead features
 java.lang.ClassNotFoundException: hudson.plugins.sshslaves.verifiers.JenkinsTrilead9VersionSupport
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
        at hudson.plugins.sshslaves.verifiers.TrileadVersionSupportManager.createVersion9Instance(TrileadVersionSupportManager.java:51)
        at hudson.plugins.sshslaves.verifiers.TrileadVersionSupportManager.getTrileadSupport(TrileadVersionSupportManager.java:32)
        at hudson.plugins.sshslaves.verifiers.SshHostKeyVerificationStrategy.getPreferredKeyAlgorithms(SshHostKeyVerificationStrategy.java:68)
        at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:797)
        at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:793)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

> [08/19/17 05:06:30] SSH Launch of dc1-b9e8394f94f3 on ecos0055 completed in 166,567 ms

![image](https://user-images.githubusercontent.com/7334961/29485453-b3313114-84ef-11e7-8353-5d6555539e1c.png)

**Comment by KostyaSha** [comment]
Well, error says that master can't access exposed ssh port on remote docker daemon.  Please describe your env setup.

**Comment by KostyaSha** [comment]
I think problem is here. Please check what version ssh-slaves plugin do you have and their changelog. Probably they broke something.
```
19-Aug-2017 05:03:44.466 WARNING [SSHLauncher.launch for 'dc1-b9e8394f94f3' node [#1]] hudson.plugins.sshslaves.verifiers.TrileadVersionSupportManager.getTrileadSupport Could not create Trilead support class. Using legacy Trilead features
java.lang.ClassNotFoundException: hudson.plugins.sshslaves.verifiers.JenkinsTrilead9VersionSupport
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285)
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
at hudson.plugins.sshslaves.verifiers.TrileadVersionSupportManager.createVersion9Instance(TrileadVersionSupportManager.java:51)
at hudson.plugins.sshslaves.verifiers.TrileadVersionSupportManager.getTrileadSupport(TrileadVersionSupportManager.java:32)
at hudson.plugins.sshslaves.verifiers.SshHostKeyVerificationStrategy.getPreferredKeyAlgorithms(SshHostKeyVerificationStrategy.java:68)
at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:797)
at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:793)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by KostyaSha** [comment]
I can suggest to use JNLP launcher. Ensure that master has correct hostname and available from daemons.

**Comment by KostyaSha** [comment]
Seems it only a warning. 
Ok, found what to check.
Please check sshd daemon logs during ssh alive checks. Either `journalctl`, either `docker logs`. Maybe sshd decided to reject authentication attempts.

**Comment by KostyaSha** [comment]
no replies...
