### ISSUE TITLE
Orphaned build agents accumulating

### ISSUE THREAD

**Issue by Starefossen** [KostyaSha/yet-another-docker-plugin#202]
Hi, and thanks for this great project.

I'm wondering if orphaned build agents is a know issue? I have a few agents running in Docker that are no longer in Jenkins with the following log message repeating in an endless loop:

```
Failing to obtain https://**REDACTED**//computer/docker-agent-8ff84c76f8fc//slave-agent.jnlp?encrypt=true
java.io.IOException: Failed to load https://**REDACTED**//computer/docker-agent-8ff84c76f8fc//slave-agent.jnlp?encrypt=true: 404 Not Found
        at hudson.remoting.Launcher.parseJnlpArguments(Launcher.java:485)
        at hudson.remoting.Launcher.run(Launcher.java:316)
        at hudson.remoting.Launcher.main(Launcher.java:277)
Waiting 10 seconds before retry
```

**Comment by witokondoria** [comment]
[This PR](https://github.com/jenkinsci/remoting/pull/193) would "solve" it, leaving the container to die peacefully if the remoting component will receive a 4XX error code

**Comment by KostyaSha** [comment]
@witokondoria not exactly. In your case slave already got config with connections, but cycles. Here first error slave disappeared while container tries reconnect. Many reasons why it may happen.
- I.e. docker daemon disappeared and jenkins found that it time to kill slave, while container has reconnect.
2)  container is on the way to run, jenkins will place config soon. Or something was aborted...

@Starefossen what launcher do you use? JNLP?

**Comment by KostyaSha** [comment]
Hmm... i run latest jenkins from master and it fails with 404. Probably something was changed in JNLP or in remoting.

**Comment by KostyaSha** [comment]
@Starefossen do you have selinux?

**Comment by Starefossen** [comment]
Yes, JNLP on latest versjon of Jenkins. No selinux.

**Comment by KostyaSha** [comment]
https://gist.github.com/KostyaSha/71be4eb3c6359d6c52da6aec56506dc4

**Comment by KostyaSha** [comment]
I don't understand why docker container is getting 404 while i can open this page...

**Comment by KostyaSha** [comment]
@Starefossen i not sure but seems they stay only when JNLP launcher failed to start and retention strategy doesn't remove it.
Could you post what you see node's launch log (go to node -> launch log)?

**Comment by KostyaSha** [comment]
And one more thing is queue lock that will be removed in #201

**Comment by KostyaSha** [comment]
@witokondoria i had jenkins with disabled security but slaves were getting 404! I enabled security and they connected
