### ISSUE TITLE
Job fails to start build container after upgrade (pending—Jenkins doesn’t have label build-agent)

### ISSUE THREAD

**Issue by urkon** [KostyaSha/yet-another-docker-plugin#219]
I have configured Jenkins in docker service. It worked fine until the upgrade and some extra plugins ware added.

Upgraded to:
* Jenkins ver. 2.89.1
* YAD 0.1.0-rc46
From: 
* Jenkins ver.2.32.2
* YAD 0.1.0-rc31

Jenkins home directory data is restored except the plugins subdir.

I use YAD plugin to start slave build agent. The slave wasn't changed. The credentials setup remains the same.
Connection test returns: 
```
com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.model.Version@115a39e3[
  apiVersion=1.24
  arch=amd64
  gitCommit=ae7d637/1.12.6
  goVersion=go1.7.6
  kernelVersion=4.13.16-100.fc25.x86_64
  operatingSystem=linux
  version=1.12.6
  buildTime=2017-07-18T16:18:12.179285019+00:00
  experimental=<null>
]
```

Job run stalls with note:  (pending—Jenkins doesn’t have label build-agent).
It doesn't even run the build container.

jenkins.log says:
```
Dec 13, 2017 11:48:37 AM hudson.slaves.NodeProvisioner$2 run
WARNING: Unexpected exception encountered while provisioning agent my/build-agent
com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.exception.DockerClientException: Could not pull image: unauthorized: authentication required
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:50)
	at com.github.kostyasha.yad.commons.DockerPullImage.exec(DockerPullImage.java:135)
	at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:229)
	at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:135)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
I do not know what to look after. Any Idea?

**Comment by urkon** [comment]
I found that the issue could be duplicate of the:
https://github.com/KostyaSha/yet-another-docker-plugin/issues/206
see: mikhirev commented on 7 Nov

**Comment by Heuvendw** [comment]
I had the same issue when upgrading to 0.1.0-rc46. When I reverted to the old 0.1.0-rc30 version it worked again. In my case I'm using a local docker docker service which has all images installed.

The message I got was:
```
com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.exception.NotFoundException:   {"message":"pull access denied for *imagename*, repository does not exist or may require 'docker login'"}
```

**Comment by KostyaSha** [comment]
@Heuvendw what pull strategy do you have?

**Comment by Heuvendw** [comment]
I'm using "Pull once but always update latest"

**Comment by KostyaSha** [comment]
@Heuvendw so did you specify docker registry credentials?

**Comment by Heuvendw** [comment]
The issue appeared to be that i did specify the pull-once however no registry credentials were provided (I do not use the registry).

Apparently in the previous version the pull once was never executed without credentials. It worked fine once more  when I changed all the instances of pull strategy to never pull.

**Comment by KostyaSha** [comment]
So does it work correct now?

**Comment by adam-kosseck** [comment]
I'm also having the same issue.
When I pull a docker image from a public docker repository (e.g. docker/slave:alpine) it works fine.
When I switch to using a docker image hosted locally (one based off docker/slave with minimal changes) it no longer works.  I get the same errors as Heuvendw.
Jenkins shows jobs as "pending - Jenkins doesn't have label slave"
Jenkins logs show:

`Jan 03, 2018 5:13:16 AM com.nirima.jenkins.plugins.docker.DockerCloud$1 run
SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='slave', connector=io.jenkins.docker.connector.DockerComputerAttachConnector@57cd7bfc, remoteFs='/home/jenkins', instanceCap=2147483647, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@7479ce5c, dockerTemplateBase=DockerTemplateBase{image='cv-utils-infra-jenkins-slave:1.0.0', pullCredentialsId='', registry=DockerRegistryEndpoint[null;credentialsId=null], dockerCommand='', hostname='', dnsHosts=[], network='bsl', volumes=[], volumesFrom2=[], environment=[], bindPorts='', bindAllPorts=false, memoryLimit=null, memorySwap=null, cpuShares=null, privileged=false, tty=false, macAddress='null', extraHosts=[]}, removeVolumes=false, pullStrategy=PULL_ALWAYS, nodeProperties=[]}' for cloud='Docker'
com.github.dockerjava.api.exception.NotFoundException: {"message":"pull access denied for cv-utils-infra-jenkins-slave, repository does not exist or may require 'docker login'"}

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:103)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:997)
	at io.netty.channel.epoll.EpollDomainSocketChannel$EpollDomainUnsafe.epollInReady(EpollDomainSocketChannel.java:138)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:401)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)`



This is with the pull strategy set to "pull all images every time".
However if I change the pull strategy to "Pull once and update latest" it works fine.
As soon as I switch the pull strategy back to "pull all images every time" it breaks again.

This seems like a bug.

I have also noted someone posting about this on [StackOverflow](https://stackoverflow.com/questions/47758187/docker-container-as-build-slave-for-jenkins).
