### ISSUE TITLE
not  find lable  and don't docker pull image

### ISSUE THREAD

**Issue by tomxiaxia** [KostyaSha/yet-another-docker-plugin#220]
for cloud='docker'
com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.exception.DockerClientException: Could not pull image

**Comment by KostyaSha** [comment]
Please provide more descriptions

**Comment by tomxiaxia** [comment]
jenkins:2.89.2
Yet Another Docker Plugin: 0.1.0-rc46
Asked to provision load: '1', for: 'docker' label
Dec 20, 2017 7:21:28 AM INFO com.github.kostyasha.yad.DockerCloud provision
Will provision 'registry.cn-hangzhou.aliyuncs.com/wenba/jenkins-slave-golang', for label: 'docker', in cloud: 'docker'
Dec 20, 2017 7:21:28 AM INFO com.github.kostyasha.yad.DockerCloud addProvisionedSlave
Provisioning 'registry.cn-hangzhou.aliyuncs.com/wenba/jenkins-slave-golang' number '0' on 'docker'; Total containers: '0'
Dec 20, 2017 7:21:28 AM INFO com.github.kostyasha.yad.commons.DockerPullImage exec
Pulling image 'registry.cn-hangzhou.aliyuncs.com/wenba/jenkins-slave-golang'. This may take awhile...
Dec 20, 2017 7:21:29 AM SEVERE com.github.kostyasha.yad.DockerCloud lambda$provision$0
Error in provisioning; template='DockerSlaveTemplate[configVersion=1,maxCapacity=10,id=ae9b02b4-6d43-4640-b77e-1281e9224e87,labelString=docker,launcher=com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher@3da910d3,remoteFs=/home/jenkins,mode=NORMAL,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@624ddee[image=registry.cn-hangzhou.aliyuncs.com/wenba/jenkins-slave-golang,pullImage=com.github.kostyasha.yad.commons.DockerPullImage@932bead3,createContainer=DockerCreateContainer[command=,commands=<null>,entrypoint=<null>,hostname=,dnsHosts=[],volumes=[],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=false,memoryLimit=0,cpuShares=<null>,privileged=false,tty=false,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=,links=[],shmSize=0,restartPolicy=DockerContainerRestartPolicy[policyName=NO,maximumRetryCount=0],workdir=,user=],stopContainer=com.github.kostyasha.yad.commons.DockerStopContainer@27f,removeContainer=com.github.kostyasha.yad.commons.DockerRemoveContainer@5aea],nodeProperties=<null>]' for cloud='docker'
com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.exception.DockerClientException: Could not pull image: Pulling registry.cn-hangzhou.aliyuncs.com/wenba/jenkins-slave-golang...
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:50)
	at com.github.kostyasha.yad.commons.DockerPullImage.exec(DockerPullImage.java:135)
	at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:229)
	at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:135)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by KostyaSha** [comment]
unclear why it happened :( Does pull work fine if you run it manually on daemon?
