### ISSUE TITLE
illegalstate exception when running tests in jenkins

### ISSUE THREAD

**Issue by amrishc** [KostyaSha/yet-another-docker-plugin#226]
I am seeing this error in the logs. Provisioning is not happeing 
Mar 09, 2018 1:07:00 AM com.github.kostyasha.yad.DockerCloud provision
INFO: Asked to provision load: '1', for: 'docker-jenkins-slave' label
Mar 09, 2018 1:07:00 AM com.github.kostyasha.yad.DockerCloud provision
INFO: Will provision 'jdoey/docker-jenkins-python-slave', for label: 'docker-jenkins-slave', in cloud: 'dockerhost'
Mar 09, 2018 1:07:00 AM com.github.kostyasha.yad.DockerCloud addProvisionedSlave
INFO: Provisioning 'jdoey/docker-jenkins-python-slave' number '0' on 'dockerhost'; Total containers: '0'
Mar 09, 2018 1:07:00 AM com.github.kostyasha.yad.commons.DockerPullImage exec
INFO: Pulling image 'jdoey/docker-jenkins-python-slave'. This may take awhile...
Mar 09, 2018 1:07:02 AM com.github.kostyasha.yad.commons.DockerPullImage exec
INFO: Finished pulling image 'jdoey/docker-jenkins-python-slave', took 1388 ms
Mar 09, 2018 1:07:02 AM com.github.kostyasha.yad.DockerCloud lambda$provision$0
SEVERE: Error in provisioning; template='DockerSlaveTemplate[configVersion=1,maxCapacity=10,id=7703cdb2-ee62-4cea-b23a-d65319ffbcad,labelString=docker-jenkins-slave,launcher=com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher@4dc3dfd3,remoteFs=/home/jenkins,mode=EXCLUSIVE,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@7066aac8[image=jdoey/docker-jenkins-python-slave,pullImage=com.github.kostyasha.yad.commons.DockerPullImage@efe32a4b,createContainer=DockerCreateContainer[command=,commands=<null>,entrypoint=<null>,hostname=,dnsHosts=[],volumes=[],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=false,memoryLimit=0,cpuShares=<null>,privileged=false,tty=false,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=,links=[],shmSize=0,restartPolicy=DockerContainerRestartPolicy[policyName=NO,maximumRetryCount=0],workdir=,user=],stopContainer=com.github.kostyasha.yad.commons.DockerStopContainer@27f,removeContainer=com.github.kostyasha.yad.commons.DockerRemoveContainer@5aea],nodeProperties=<null>]' for cloud='dockerhost'
java.lang.IllegalStateException: Container '177b764380e5c6f1bb140bf5f4a088e17d976c19ddcfc4327e41e28ebe412ddf' is not running!
	at com.github.kostyasha.yad.launcher.DockerComputerLauncher.waitUp(DockerComputerLauncher.java:56)
	at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:94)
	at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:259)
	at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:135)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

OS - Ubuntu 16.04
Jenkins - 2.89.4

**Comment by amrishc** [comment]
Here is the config.xml


<?xml version='1.0' encoding='UTF-8'?>
<hudson>
  <disabledAdministrativeMonitors/>
  <version>2.89.4</version>
  <installState>
    <isSetupComplete>true</isSetupComplete>
    <name>RUNNING</name>
  </installState>
  <numExecutors>2</numExecutors>
  <mode>NORMAL</mode>
  <useSecurity>true</useSecurity>
  <authorizationStrategy class="hudson.security.FullControlOnceLoggedInAuthorizationStrategy">
    <denyAnonymousReadAccess>true</denyAnonymousReadAccess>
  </authorizationStrategy>
  <securityRealm class="hudson.security.HudsonPrivateSecurityRealm">
    <disableSignup>true</disableSignup>
    <enableCaptcha>false</enableCaptcha>
  </securityRealm>
  <disableRememberMe>false</disableRememberMe>
  <projectNamingStrategy class="jenkins.model.ProjectNamingStrategy$DefaultProjectNamingStrategy"/>
  <workspaceDir>${JENKINS_HOME}/workspace/${ITEM_FULLNAME}</workspaceDir>
  <buildsDir>${ITEM_ROOTDIR}/builds</buildsDir>
  <jdks/>
  <viewsTabBar class="hudson.views.DefaultViewsTabBar"/>
  <myViewsTabBar class="hudson.views.DefaultMyViewsTabBar"/>
  <clouds>
    <com.github.kostyasha.yad.DockerCloud plugin="yet-another-docker-plugin@0.1.0-rc47">
      <name>dockerhost</name>
      <provisionedImages/>
      <templates>
        <com.github.kostyasha.yad.DockerSlaveTemplate>
          <id>7703cdb2-ee62-4cea-b23a-d65319ffbcad</id>
          <labelString>docker-jenkins-slave</labelString>
          <launcher class="com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher">
            <sshConnector plugin="ssh-slaves@1.26">
              <port>22</port>
              <credentialsId>docker-jenkins-slave</credentialsId>
              <jvmOptions></jvmOptions>
              <javaPath></javaPath>
              <maxNumRetries>0</maxNumRetries>
              <retryWaitTime>0</retryWaitTime>
              <sshHostKeyVerificationStrategy class="hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy"/>
            </sshConnector>
          </launcher>
          <remoteFs>/home/jenkins</remoteFs>
          <mode>EXCLUSIVE</mode>
          <retentionStrategy class="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">
            <idleMinutes>10</idleMinutes>
            <idleMinutes defined-in="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">10</idleMinutes>
          </retentionStrategy>
          <numExecutors>1</numExecutors>
          <dockerContainerLifecycle>
            <image>jdoey/docker-jenkins-python-slave</image>
            <pullImage>
              <pullStrategy>PULL_LATEST</pullStrategy>
              <credentialsId>my-docker-hub2</credentialsId>
            </pullImage>
            <createContainer>
              <command></command>
              <hostname></hostname>
              <dnsHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </dnsHosts>
              <volumes class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </volumes>
              <volumesFrom class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </volumesFrom>
              <environment class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </environment>
              <bindPorts></bindPorts>
              <bindAllPorts>false</bindAllPorts>
              <memoryLimit>0</memoryLimit>
              <privileged>false</privileged>
              <tty>false</tty>
              <extraHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </extraHosts>
              <devices class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </devices>
              <cpusetCpus></cpusetCpus>
              <cpusetMems></cpusetMems>
              <links class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </links>
              <shmSize>0</shmSize>
              <restartPolicy>
                <policyName>NO</policyName>
                <maximumRetryCount>0</maximumRetryCount>
              </restartPolicy>
              <workdir></workdir>
              <user></user>
            </createContainer>
            <stopContainer>
              <timeout>10</timeout>
            </stopContainer>
            <removeContainer>
              <removeVolumes>true</removeVolumes>
              <force>false</force>
            </removeContainer>
          </dockerContainerLifecycle>
          <configVersion>1</configVersion>
          <maxCapacity>10</maxCapacity>
        </com.github.kostyasha.yad.DockerSlaveTemplate>
      </templates>
      <containerCap>50</containerCap>
      <connector>
        <serverUrl>tcp://138.68.224.237:2376</serverUrl>
        <credentialsId>dockerhost</credentialsId>
        <connectorType>NETTY</connectorType>
      </connector>
    </com.github.kostyasha.yad.DockerCloud>
  </clouds>
  <quietPeriod>5</quietPeriod>
  <scmCheckoutRetryCount>0</scmCheckoutRetryCount>
  <views>
    <hudson.model.AllView>
      <owner class="hudson" reference="../../.."/>
      <name>all</name>
      <filterExecutors>false</filterExecutors>
      <filterQueue>false</filterQueue>
      <properties class="hudson.model.View$PropertyList"/>
    </hudson.model.AllView>
  </views>
  <primaryView>all</primaryView>
  <slaveAgentPort>-1</slaveAgentPort>
  <disabledAgentProtocols>
    <string>JNLP-connect</string>
    <string>JNLP2-connect</string>
  </disabledAgentProtocols>
  <label></label>
  <crumbIssuer class="hudson.security.csrf.DefaultCrumbIssuer">
    <excludeClientIPFromCrumb>false</excludeClientIPFromCrumb>
  </crumbIssuer>
  <nodeProperties/>
  <globalNodeProperties/>
</hudson>

**Comment by amrishc** [comment]
sorry it was an issue with my template. Rookie mistake.
