### ISSUE TITLE
Containers are not removed if provisioning error occurs

### ISSUE THREAD

**Issue by mikhirev** [KostyaSha/yet-another-docker-plugin#251]
Hi!

If for some reason a provisioning error occurs, created container is not cleaned up. As Jenkins keep trying to provision a new container, it leads to disk space exhaustion.

**Comment by KostyaSha** [comment]
Hi, please provide any logs/configuration.

**Comment by mikhirev** [comment]
E. g. specify `/bin/false` as docker command.

```
Apr 23, 2019 3:20:59 PM INFO com.github.kostyasha.yad.DockerCloud provision

Asked to provision load: '1', for: 'testtesttest' label

Apr 23, 2019 3:20:59 PM INFO com.github.kostyasha.yad.DockerCloud provision

Will provision 'registry.i.drweb.ru/build-containers/livedisk-builder:xenial', for label: 'testtesttest', in cloud: 'docker@buildbot3'

Apr 23, 2019 3:20:59 PM INFO com.github.kostyasha.yad.DockerCloud addProvisionedSlave

Provisioning 'registry.i.drweb.ru/build-containers/livedisk-builder:xenial' number '0' on 'docker@buildbot3'; Total containers: '0'

Apr 23, 2019 3:21:00 PM SEVERE com.github.kostyasha.yad.DockerCloud lambda$provision$0

Error in provisioning; template='DockerSlaveTemplate[configVersion=1,maxCapacity=10,id=568fedb4-96a7-4679-8fba-23bb4d450a08,labelString=docker testtesttest,launcher=com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher@756ab1dd,remoteFs=/home/jenkins,mode=EXCLUSIVE,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@4976fcf4[image=registry.i.drweb.ru/build-containers/livedisk-builder:xenial,pullImage=DockerPullImage[pullStrategy=PULL_LATEST,credentialsId=d3994fe0-96f0-4f34-bbb0-7ef9605dac6b,registriesCreds=<null>,connector=<null>],createContainer=DockerCreateContainer[command=/bin/false,commands=<null>,entrypoint=<null>,hostname=,dnsHosts=[],volumes=[],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=false,memoryLimit=0,cpuShares=<null>,privileged=false,tty=false,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=,links=[],dockerLabels=[],shmSize=0,restartPolicy=DockerContainerRestartPolicy[policyName=NO,maximumRetryCount=0],workdir=,user=],stopContainer=DockerStopContainer[timeout=10,connector=<null>],removeContainer=DockerRemoveContainer[removeVolumes=true,force=false,connector=<null>]],nodeProperties=<null>]' for cloud='docker@buildbot3'
java.lang.IllegalStateException: Container 'ea82de4a807e027b0bed09c046254c1dee76d80abe8ac067f91c77f72af94414' is not running!
	at com.github.kostyasha.yad.launcher.DockerComputerLauncher.waitUp(DockerComputerLauncher.java:56)
	at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:94)
	at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:259)
	at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:135)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mikhirev** [comment]
Another example is in #257: containers are not removed in that case too.

**Comment by KostyaSha** [comment]
What retention strategy is used?

**Comment by KostyaSha** [comment]
Ok, i found one place where cleanup makes sense, will PR

**Comment by KostyaSha** [comment]
https://github.com/KostyaSha/yet-another-docker-plugin/pull/264
