### ISSUE TITLE
Error connecting to containers using SSH

### ISSUE THREAD

**Issue by qclemence** [KostyaSha/yet-another-docker-plugin#257]
Hi,
After upgrading the Jenkins plugin SSH Slaves to version 1.30.0, I get the following error when I run a job :

```
Jun 12, 2019 8:17:36 AM com.github.kostyasha.yad.DockerCloud provision
INFO: Asked to provision load: '1', for: 'dind' label
Jun 12, 2019 8:17:36 AM com.github.kostyasha.yad.DockerCloud provision
INFO: Will provision 'dind:1.0', for label: 'dind', in cloud: 'SlaveLocal'
Jun 12, 2019 8:17:36 AM com.github.kostyasha.yad.DockerCloud addProvisionedSlave
INFO: Provisioning 'dind:1.0' number '2' on 'SlaveLocal'; Total containers: '2'
Jun 12, 2019 8:17:37 AM com.github.kostyasha.yad.utils.HostAndPortChecker bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:32897 (try 1/60) - There was a problem while connecting to localhost:32897
Jun 12, 2019 8:17:39 AM com.github.kostyasha.yad.utils.HostAndPortChecker bySshWithEveryRetryWaitFor
INFO: SSH port is open on localhost:32897
Jun 12, 2019 8:17:39 AM com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher getSSHLauncher
INFO: Creating slave SSH launcher for 'localhost:32897'. Cloud: 'SlaveLocal'. Template: 'dind:1.0'
Jun 12, 2019 8:17:46 AM hudson.slaves.NodeProvisioner$2 run
WARNING: Unexpected exception encountered while provisioning agent dind:1.0
java.lang.NoSuchMethodError: hudson.plugins.sshslaves.SSHConnector.getCredentials()Lcom/cloudbees/plugins/credentials/common/StandardUsernameCredentials;
        at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.getSSHLauncher(DockerComputerSSHLauncher.java:122)
        at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.getPreparedLauncher(DockerComputerSSHLauncher.java:62)
        at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:265)
        at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:135)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

In version 1.30.0 of the SSH Slaves plugin, some deprecated codes, and especially the getCredentials method, have been removed.

Plugin versions :
SSH Slaves 1.30.0
Yet Another Docker Plugin 0.1.0-rc52

Jenkins core version : 2.180

Regards

**Comment by wgillaspy** [comment]
Breaking Change in ssh-slaves release notes: https://github.com/jenkinsci/ssh-slaves-plugin/blob/master/CHANGELOG.md

**Comment by KostyaSha** [comment]
`Upgrade Jenkins core to 2.150.1, I will support 2 LTS versions`

Sounds like current maintainer doesn't work with enterprise and huge systems, i can't require half year LTS (while jenkins LTS is just stable version). I will try to look wether it's possible to use existing methods.

**Comment by wmorrell** [comment]
I ran into this, and have been running with `ssh-slaves-plugin` kept at 1.29.4 in the mean time to keep things working.

From looking at the code, I *think* it can be a simple fix of hoisting the API used in `ssh-slaves-plugin` into this plugin. It's a few lines of code, basically change `sshConnector.getCredentials()` to `SSHLauncher.lookupSystemCredentials(sshConnector.getCredentialsId()`.

I'm attempting to build now and will make a PR shortly if I can figure out how to test and verify that it works.

**Comment by Starefossen** [comment]
Just got hit by this ourself, downgrading `ssh-slaves-plugin` to 1.29.4 solved the problem.

**Comment by bcooksley** [comment]
Following the above merge request we're now closer to working with the SSH Slaves Plugin.
It now fails with:

`2019-09-26 18:00:41.892+0000 [id=52]    WARNING hudson.slaves.NodeProvisioner#lambda$update$6: Unexpected exception encountered while provisioning agent kdeorg/ci-suse-qt512
java.lang.IllegalAccessError: tried to access field hudson.plugins.sshslaves.SSHConnector.jvmOptions from class com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher
        at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.getSSHLauncher(DockerComputerSSHLauncher.java:126)
        at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.getPreparedLauncher(DockerComputerSSHLauncher.java:63)
        at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:265)
        at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:135)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

Will continue to downgrade it for now - if we could get a fix though it would be nice.

**Comment by KostyaSha** [comment]
The right fix is migrate contriguration into internal class and that's all

**Comment by wmorrell** [comment]
Oh. I didn't even think to look at what else changed in `ssh-slaves-plugin`. It's annoying that the interface changed wholesale with a minor version bump from 1.29.x to 1.30.x. All the properties except for `SSHConnector.port` converted from `public final` to `private` access and getters/setters added. 

Agreed that the best fix is to have configuration in an internal class, and not depend on specific versions of configuration in other plugins. Updating code from PR would tie specific versions together, e.g. must use `yet-another-docker-plugin==0.1.1` with `ssh-slaves-plugin<=1.29.4` and must use `yet-another-docker-plugin==0.1.4` with `ssh-slaves-plugin>=1.30.2`. Mixing up the versions would always break. While moving the entire thing internal means this is compatible with both 1.29.4 and 1.30.2 simultaneously.

**Comment by mikhirev** [comment]
Still does not work...

I upgraded yadp to 0.1.4 and ssh slaves plugin to 1.31.0. Agents fail to start.

```
ERROR: Launching agent process aborted.
java.lang.InterruptedException: Validate configuration:
The selected credentials cannot be found

	at hudson.plugins.sshslaves.SSHLauncher.checkConfig(SSHLauncher.java:900)
	at hudson.plugins.sshslaves.SSHLauncher.launch(SSHLauncher.java:402)
	at hudson.slaves.DelegatingComputerLauncher.launch(DelegatingComputerLauncher.java:64)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:297)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

After I reverted ssh slaves to 1.29.4, there's still some problem with credentials:

```
SSHLauncher{host='myhost', port=33546, credentialsId='', jvmOptions='', javaPath='', prefixStartSlaveCmd='', suffixStartSlaveCmd='', launchTimeoutSeconds=210, maxNumRetries=0, retryWaitTime=0, sshHostKeyVerificationStrategy=hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy, tcpNoDelay=true, trackCredentials=true}
[10/16/19 18:53:51] [SSH] Opening SSH connection to buildbot3.i.drweb.ru:33546.
[10/16/19 18:53:51] [SSH] WARNING: SSH Host Keys are not being verified. Man-in-the-middle attacks may be possible against this connection.
Cannot find SSH User credentials with id: null
[10/16/19 18:53:51] Launch failed - cleaning up connection
[10/16/19 18:53:51] [SSH] Connection closed.
```

After I also reverted yadp to 0.1.3, I found that all container SSH credentials in docker templates are reset to `- none -`. Only when I restored credentials, I could lauch jobs.
