### ISSUE TITLE
plugin not working with >= ssh-slaves-plugin-1.30.0

### ISSUE THREAD

**Issue by rdevries** [KostyaSha/yet-another-docker-plugin#278]
After the update of the ssh-slaves plugin to 1.30.0 we are unable to get the containers running again. (1.28.1 is working fine, 1.31.0 is broken as well) It keeps provisioning and after a little bit of research we found out that it somehow was unable to find the the selected credentials for the docker container.

I also created an issue in Jira for jenkins and the ssh-slaves-plugin (https://issues.jenkins-ci.org/browse/JENKINS-59879) because i don't know which one is the cause of the issue.

We use the SSH Docker Computer Launcher with SSH credentials (username password).
I tried changing the Host Key Verification Strategy to Non verifying Verification Strategy but that didnt help either.

**Comment by KostyaSha** [comment]
What plugin version do you use?

**Comment by KostyaSha** [comment]
please use 0.1.5

**Comment by rdevries** [comment]
Oh, the plugin manager doesnt prompt that version.

**Comment by rdevries** [comment]
where can i find 0.1.5 ? 0.1.4 seems to be the latest (http://mirrors.jenkins-ci.org/plugins/yet-another-docker-plugin/)

**Comment by KostyaSha** [comment]
https://repo.jenkins-ci.org/releases/com/github/kostyasha/yet-another-docker/yet-another-docker-plugin/0.1.5/yet-another-docker-plugin-0.1.5.hpi

**Comment by rdevries** [comment]
Updated... the problem remains..
```ERROR: Launching agent process aborted.
java.lang.InterruptedException: Validate configuration:
The selected credentials cannot be found

	at hudson.plugins.sshslaves.SSHLauncher.checkConfig(SSHLauncher.java:900)
	at hudson.plugins.sshslaves.SSHLauncher.launch(SSHLauncher.java:402)
	at hudson.slaves.DelegatingComputerLauncher.launch(DelegatingComputerLauncher.java:64)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:297)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by KostyaSha** [comment]
> the update of the ssh-slaves plugin to 1.30.0

https://github.com/jenkinsci/ssh-slaves-plugin/commit/62346f1c0bb4940acd22c7dacf612e15bc97c3ab

More and more brekages from ssh-slaves-plugin. Please update it to the latest

**Comment by rdevries** [comment]
yeah that fix is included in version 1.30.1
The version that we are using is version 1.31.0 which should include it as well.

**Comment by KostyaSha** [comment]
So config works ok, but credentials lookup fails

**Comment by KostyaSha** [comment]
Is it still actual?

**Comment by rdevries** [comment]
Sorry, 

I haven't been able to look into this anymore.
I no long work on this project either, so you can close it if you want.
