### ISSUE TITLE
unix:///var/run/docker.sock does not work as provider

### ISSUE THREAD

**Issue by kuisathaverat** [KostyaSha/yet-another-docker-plugin#280]
it seems to not work with *unix:///var/run/docker.sock*
as provider this line is the culprit https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/launcher/DockerComputerSSHLauncher.java#L171 this return *unix:///var/run/docker.sock* and it is not an URI that return a host, getHosts() return *null*

```
SEVERE: Removing 9aaf475f142eff47e1b8aa560fa7f5a53369b3988dd9e6ee0daa7d759e9c846f container.
Oct 22, 2019 9:51:16 PM com.github.kostyasha.yad.DockerCloud lambda$provision$0
SEVERE: Error in provisioning; template='DockerSlaveTemplate[configVersion=1,maxCapacity=10,id=b158c964-73b4-4d61-8f1b-4c2e6195f473,labelString=docker-yad,launcher=com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher@145678d2,remoteFs=/home/jenkins,mode=NORMAL,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@1ec188dc[image=jenkins/ssh-slave:jdk11,pullImage=DockerPullImage[pullStrategy=PULL_LATEST,credentialsId=,registriesCreds=<null>,connector=<null>],createContainer=DockerCreateContainer[command=,commands=<null>,entrypoint=<null>,hostname=docker-agent,dnsHosts=[],volumes=[],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=false,memoryLimit=2000,cpuShares=2,privileged=false,tty=false,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=,links=[],dockerLabels=[],shmSize=2000,restartPolicy=DockerContainerRestartPolicy[policyName=NO,maximumRetryCount=0],workdir=/home/jenkins,user=jenkins],stopContainer=DockerStopContainer[timeout=10,connector=<null>],removeContainer=DockerRemoveContainer[removeVolumes=true,force=true,connector=<null>]],nodeProperties=<null>]' for cloud='YAD'
java.lang.NullPointerException
        at com.github.kostyasha.yad_docker_java.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
        at com.github.kostyasha.yad_docker_java.com.google.common.net.HostAndPort.fromString(HostAndPort.java:168)
        at com.github.kostyasha.yad_docker_java.com.google.common.net.HostAndPort.fromParts(HostAndPort.java:135)
        at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.getHostAndPort(DockerComputerSSHLauncher.java:174)
        at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:105)
        at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:253)
        at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:135)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

Oct 22, 2019 9:51:19 PM hudson.model.AsyncPeriodicWork$1 run
```

**Comment by KostyaSha** [comment]
What is the use case? I would also suggest to use JNLP launcher, it needs only correct address of jenkins available from container internals

**Comment by kuisathaverat** [comment]
If the setting does not work, remove it from the UI

**Comment by KostyaSha** [comment]
Could you describe your network configuration? Via what address jenkins can access container? Because if both in containers extra-logic is needed to guess IP of container. I think some fallback could be added as null is clear here, but i can't imaging setup.

**Comment by kuisathaverat** [comment]
It was during the configuration of an environment to test [JENKINS-59879](https://issues.jenkins-ci.org/browse/JENKINS-59879), I hit exception after exception until I finally configured the plugin, you can read my comments in that issue, you can check my final environment configured at [JCasC environment for JENKINS-59879](https://github.com/kuisathaverat/jenkins-issues/tree/master/JENKINS-59879)

**Comment by KostyaSha** [comment]
ssh-credentials will double check them. So jenkins and container is in one network the it should work. Looks like the only thing jenkins should know about agent is network name, then it can get it's IP

**Comment by KostyaSha** [comment]
> , you can read my comments in that issue,

Force remove option is available in DockerRemoveContainer settings. No need to fill all options, only key related for template and connector. Jasc  support will implement soon. #283 should help resolve ip address in your variant plus added fallback.
