### ISSUE TITLE
Stop Container Settings

### ISSUE THREAD

**Issue by rmshnair** [KostyaSha/yet-another-docker-plugin#289]
Container is killed by 5 mins or 10 mins automatically irrespective of values in stop container settings. unable to increase the container stop timout more than 10 mins

**Comment by KostyaSha** [comment]
Does UI load a value after you set it and reload page?

**Comment by rmshnair** [comment]
![image](https://user-images.githubusercontent.com/70548342/91787838-c0e64080-ebd8-11ea-9585-17eca1ca63ab.png)
it loads, however, the container is killed in 5 or 10 mins exactly while the container still busy serving its master

**Comment by KostyaSha** [comment]
Could you enable debug in daemon and check what value is send to daemon? That will very help

**Comment by rmshnair** [comment]
looking deeper into this problem, it is not a timeout issue. due to some issues, one of the thread is dead

A thread (Thread-3592/4897) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.io.IOException: Write end dead
	at java.io.PipedInputStream.read(PipedInputStream.java:310)
	at java.io.PipedInputStream.read(PipedInputStream.java:377)
	at java.io.InputStream.read(InputStream.java:101)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.netty.NettyInvocationBuilder$1.read(NettyInvocationBuilder.java:245)
Caused: java.lang.RuntimeException
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.netty.NettyInvocationBuilder$1.read(NettyInvocationBuilder.java:247)
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.netty.NettyInvocationBuilder$1.run(NettyInvocationBuilder.java:257)
	at java.lang.Thread.run(Thread.java:748)
