### ISSUE TITLE
Unix protocol does not work

### ISSUE THREAD

**Issue by dasJ** [KostyaSha/yet-another-docker-plugin#34]
When I try to connect to docker via the unix socket protocol, and hit the test button, I get the following exception:
```
java.lang.UnsatisfiedLinkError: com.github.kostyasha.yad.docker_java.org.newsclub.net.unix.NativeUnixSocket.setCreated(Lcom/github/kostyasha/yad/docker_java/org/newsclub/net/unix/AFUNIXSocket;)V
        at com.github.kostyasha.yad.docker_java.org.newsclub.net.unix.NativeUnixSocket.setCreated(Native Method)
        at com.github.kostyasha.yad.docker_java.org.newsclub.net.unix.AFUNIXSocket.<init>(AFUNIXSocket.java:36)
        at com.github.kostyasha.yad.docker_java.org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:50)
        at com.github.kostyasha.yad.docker_java.com.github.dockerjava.jaxrs.ApacheUnixSocket.<init>(ApacheUnixSocket.java:53)
        at com.github.kostyasha.yad.docker_java.com.github.dockerjava.jaxrs.UnixConnectionSocketFactory.createSocket(UnixConnectionSocketFactory.java:65)
        at com.github.kostyasha.yad.docker_java.org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:108)
        at com.github.kostyasha.yad.docker_java.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
        at com.github.kostyasha.yad.docker_java.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
        at com.github.kostyasha.yad.docker_java.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
        at com.github.kostyasha.yad.docker_java.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
        at com.github.kostyasha.yad.docker_java.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
        at com.github.kostyasha.yad.docker_java.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at com.github.kostyasha.yad.docker_java.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at com.github.kostyasha.yad.docker_java.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at com.github.kostyasha.yad.docker_java.com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:441)
        at com.github.kostyasha.yad.docker_java.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)
        at com.github.kostyasha.yad.docker_java.org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
        at com.github.kostyasha.yad.docker_java.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at com.github.kostyasha.yad.docker_java.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at com.github.kostyasha.yad.docker_java.org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at com.github.kostyasha.yad.docker_java.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
        at com.github.kostyasha.yad.docker_java.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
        at com.github.kostyasha.yad.docker_java.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:408)
        at com.github.kostyasha.yad.docker_java.org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:308)
        at com.github.kostyasha.yad.docker_java.com.github.dockerjava.jaxrs.VersionCmdExec.execute(VersionCmdExec.java:25)
        at com.github.kostyasha.yad.docker_java.com.github.dockerjava.jaxrs.VersionCmdExec.execute(VersionCmdExec.java:12)
        at com.github.kostyasha.yad.docker_java.com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
        at com.github.kostyasha.yad.docker_java.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
        at com.github.kostyasha.yad.DockerConnector$DescriptorImpl.doTestConnection(DockerConnector.java:189)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:324)
        at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:167)
        at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:100)
        at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:233)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
        at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:80)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
        at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
        at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by KostyaSha** [comment]
Well, first of all jenkins and docker expected to be on separate environments. Secondary if it doesn't work, then it docker-java issue. Thirdly i'm in process on moving to netty #30 and you could try again after i move to it :)
Or... it shading issue...
In any case please provide more detailed log.

**Comment by dasJ** [comment]
I'm using yad 0.1.0-rc9 on a Jenkins 2.7.

Everything is running on Arch Linux (current version).

But I agree, we should leave this until you merged #30.

**Comment by KostyaSha** [comment]
Could you try master version?

**Comment by KostyaSha** [comment]
no replies.
