### ISSUE TITLE
unix:/// results into stacktrace

### ISSUE THREAD

**Issue by MansM** [KostyaSha/yet-another-docker-plugin#49]
Jenkins docker-image jenkinci/jenkins:2.9
Plugin version: 0.1.0-rc14
Docker version 1.12.0-rc2-beta16
connectionstring: unix:///var/run/docker.sock (which worked in the other plugin ;-) )
```
javax.servlet.ServletException: java.lang.NoClassDefFoundError: io/netty/channel/epoll/NativeStaticallyReferencedJniMethods
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:233)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: io/netty/channel/epoll/NativeStaticallyReferencedJniMethods
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.github.kostyasha.yad.docker_java.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:193)
	at com.github.kostyasha.yad.docker_java.io.netty.channel.epoll.Native.<clinit>(Native.java:60)
	at com.github.kostyasha.yad.docker_java.io.netty.channel.epoll.IovArray.<clinit>(IovArray.java:57)
	at com.github.kostyasha.yad.docker_java.io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:57)
	at com.github.kostyasha.yad.docker_java.io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:78)
	at com.github.kostyasha.yad.docker_java.io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:30)
	at com.github.kostyasha.yad.docker_java.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:77)
	at com.github.kostyasha.yad.docker_java.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:48)
	at com.github.kostyasha.yad.docker_java.io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:57)
	at com.github.kostyasha.yad.docker_java.io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:63)
	at com.github.kostyasha.yad.docker_java.io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:51)
	at com.github.kostyasha.yad.docker_java.com.github.dockerjava.netty.DockerCmdExecFactoryImpl$UnixDomainSocketInitializer.init(DockerCmdExecFactoryImpl.java:218)
	at com.github.kostyasha.yad.docker_java.com.github.dockerjava.netty.DockerCmdExecFactoryImpl.init(DockerCmdExecFactoryImpl.java:194)
	at com.github.kostyasha.yad.docker_java.com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:159)
	at com.github.kostyasha.yad.client.ClientBuilderForConnector.build(ClientBuilderForConnector.java:163)
	at com.github.kostyasha.yad.DockerConnector$DescriptorImpl.doTestConnection(DockerConnector.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:324)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:167)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:100)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	... 45 more
Caused by: java.lang.ClassNotFoundException: io.netty.channel.epoll.NativeStaticallyReferencedJniMethods
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 76 more
```

**Comment by KostyaSha** [comment]
Maybe related to https://github.com/docker-java/docker-java/issues/537#issuecomment-227875085
Socket connection is huge problem, i switched YAD to netty because it will support async commands.
I'm using this commands for docker-beta in my env https://github.com/KostyaSha/notes/wiki/Docker

**Comment by MansM** [comment]
this works a bit, but now I am stuck the plugin really only wants to connect through localhost:3277x

**Comment by KostyaSha** [comment]
any logs?

**Comment by KostyaSha** [comment]
Do you use sshlauncher or jnlp? I would suggest to use jnlp launcher, it will connect to jenkins and not jenkins->container. (We are still writing better documentation :( )

**Comment by MansM** [comment]
logs for ssh launcher:
jenkins    | Jun 29, 2016 1:42:58 PM com.github.kostyasha.yad.DockerCloud provision
jenkins    | INFO: Asked to provision load: '1', for: 'buildslave-centos6' label
jenkins    | Jun 29, 2016 1:42:58 PM com.github.kostyasha.yad.DockerCloud provision
jenkins    | INFO: Will provision 'buildslave-centos6', for label: 'buildslave-centos6', in cloud: ''
jenkins    | Jun 29, 2016 1:42:58 PM com.github.kostyasha.yad.DockerCloud addProvisionedSlave
jenkins    | INFO: Provisioning 'buildslave-centos6' number '0' on ''; Total containers: '0'
jenkins    | Jun 29, 2016 1:42:58 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
jenkins    | INFO: Started provisioning buildslave-centos6 from  with 1 executors. Remaining excess workload: 0
jenkins    | Jun 29, 2016 1:43:36 PM com.github.kostyasha.yad.DockerCloud provisionWithWait
jenkins    | INFO: Trying to run container for buildslave-centos6
jenkins    | Jun 29, 2016 1:43:27 PM com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher getSSHLauncher
jenkins    | INFO: Creating slave SSH launcher for 'localhost:32822'
jenkins    | Jun 29, 2016 1:43:36 PM hudson.slaves.NodeProvisioner$2 run
jenkins    | INFO: buildslave-centos6 provisioning successfully completed. We have now 2 computer(s)
jenkins    | [06/29/16 13:43:36] SSH Launch of -4a28c7876db7 on localhost failed in 7 ms
enkins    | Jun 29, 2016 1:43:46 PM com.github.kostyasha.yad.DockerCloud provision
jenkins    | INFO: Asked to provision load: '1', for: 'buildslave-centos6' label
jenkins    | Jun 29, 2016 1:43:46 PM com.github.kostyasha.yad.DockerCloud provision
jenkins    | INFO: Will provision 'buildslave-centos6', for label: 'buildslave-centos6', in cloud: ''
jenkins    | Jun 29, 2016 1:43:46 PM com.github.kostyasha.yad.DockerCloud addProvisionedSlave
jenkins    | INFO: Provisioning 'buildslave-centos6' number '1' on ''; Total containers: '1'
jenkins    | Jun 29, 2016 1:43:46 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
jenkins    | INFO: Started provisioning buildslave-centos6 from  with 1 executors. Remaining excess workload: 0
jenkins    | Jun 29, 2016 1:43:46 PM com.github.kostyasha.yad.DockerCloud provisionWithWait
jenkins    | INFO: Trying to run container for buildslave-centos6

**Comment by KostyaSha** [comment]
Please try JNLP launcher, it more lightweight and wouldn't have issues with searching network connections behind the nat/expose.

**Comment by KostyaSha** [comment]
WIP added switch in configuration between NETTY and Jersey. 
Unix socket issue is docker-java library issue. When it will support, it will work here.
Closing as nothing that could be done in context of this plugin.
