### ISSUE TITLE
Slave is created even when connection to container fails

### ISSUE THREAD

**Issue by dasJ** [KostyaSha/yet-another-docker-plugin#50]
When I have a broken Docker image that can not start SSH, yad tries to connect to it 60 times. But even when all 60 attempts fail and an exception is thrown, the slave is created:

```
Jul 06, 2016 11:24:08 AM com.github.kostyasha.yad.utils.HostAndPortChecker bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:32793 (try 60/60) - There was a problem while connecting to localhost:32793
Jul 06, 2016 11:24:08 AM com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher waitUp
WARNING: Can't connect to ssh                              
java.io.IOException: There was a problem while connecting to localhost:32793
at com.trilead.ssh2.Connection.connect(Connection.java:818)
        at com.github.kostyasha.yad.utils.HostAndPortChecker.bySshWithEveryRetryWaitFor(HostAndPortChecker.java:89)
        at com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:90)
        at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:216)
        at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:117)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at com.trilead.ssh2.transport.TransportManager.establishConnection(TransportManager.java:354)
        at com.trilead.ssh2.transport.TransportManager.initialize(TransportManager.java:467)
        at com.trilead.ssh2.Connection.connect(Connection.java:758)
        ... 9 more
Jul 06, 2016 11:24:08 AM com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher getSSHLauncher
INFO: Creating slave SSH launcher for 'localhost:32793'
[07/06/16 11:24:10] SSH Launch of Localhost-2072c43aac2a on localhost failed in 9 ms
Jul 06, 2016 11:24:10 AM hudson.slaves.NodeProvisioner$2 run
INFO: my/image provisioning successfully completed. We have now 2 computer(s)
```

**Comment by KostyaSha** [comment]
You are using SSHLauncher it requires:
- right configuration for ssh Exposed port
- jenkins should able connect to this exposed port
- ssh credentials should be right

I would suggest experiment with JNLPLauncher

**Comment by dasJ** [comment]
No, I'm not reporting that the container does not start, this is likely a problem with my images.

My problem is that yad creates a slave even when the connection fails. It shouldn't do that IMO because the slave will not be functional.

**Comment by KostyaSha** [comment]
It must create slave because connection and launcher is tied to slave. Slave would be functional when it connects and start accepting jobs. Also created slave prevents from spawning new slaves. 
When slave fails it disappears automatically and tries to launch/provision it again.
