### ISSUE TITLE
NPE in SslHandler.unwrap. 

### ISSUE THREAD

**Issue by Mishail** [KostyaSha/yet-another-docker-plugin#57]
We have a docker host with our cutom images to spin up docker slaves. The docker host exposes its socket over TCP, protected by TLS.

Everything worked fine for us, but of of the sudded we started getting weird exceptions.

Nothing was changed at the docker host, and I could not find any changes in our Jenkins as well.

I was trying both 0.1.0-rc14 and 0.1.0-rc15 with the same result.

Here is the exception:
```
Aug 02, 2016 10:21:20 AM com.github.kostyasha.yad.DockerCloud lambda$provision$0
SEVERE: Error in provisioning; template='DockerSlaveTemplate[id=6079d8b2-e594-475b-bcb3-df9f42a5bd72,labelString=platfrom-c,launcher=com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher@73b4411f,remoteFsMapping=,remoteFs=/home/jenkins,maxCapacity=1,mode=NORMAL,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@6e210a53[image=docker.apple.com/athena-c/centos7-clang:1.5.0,pullImage=com.github.kostyasha.yad.commons.DockerPullImage@953c5e6c,createContainer=DockerCreateContainer[command=,hostname=,dnsHosts=[],volumes=[],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=false,memoryLimit=0,cpuShares=<null>,privileged=false,tty=false,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=],stopContainer=com.github.kostyasha.yad.commons.DockerStopContainer@27f,removeContainer=com.github.kostyasha.yad.commons.DockerRemoveContainer@5b0f],nodeProperties=[]]' for cloud='athena11'
com.github.kostyasha.yad.docker_java.io.netty.handler.codec.DecoderException: java.lang.NullPointerException
        at com.github.kostyasha.yad.docker_java.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:418)
        at com.github.kostyasha.yad.docker_java.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
        at com.github.kostyasha.yad.docker_java.io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at com.github.kostyasha.yad.docker_java.io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
        at com.github.kostyasha.yad.docker_java.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at com.github.kostyasha.yad.docker_java.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
        at com.github.kostyasha.yad.docker_java.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
        at com.github.kostyasha.yad.docker_java.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
        at com.github.kostyasha.yad.docker_java.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
        at com.github.kostyasha.yad.docker_java.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
        at com.github.kostyasha.yad.docker_java.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
        at com.github.kostyasha.yad.docker_java.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
        at com.github.kostyasha.yad.docker_java.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at com.github.kostyasha.yad.docker_java.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at java.lang.System.arraycopy(Native Method)
        at com.sun.crypto.provider.GCTR.reset(GCTR.java:125)
        at com.sun.crypto.provider.GCTR.doFinal(GCTR.java:116)
        at com.sun.crypto.provider.GaloisCounterMode.doLastBlock(GaloisCounterMode.java:343)
        at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:511)
        at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1023)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:960)
        at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:479)
        at javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:830)
        at javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
        at javax.crypto.Cipher.doFinal(Cipher.java:2416)
        at sun.security.ssl.CipherBox.decrypt(CipherBox.java:535)
        at sun.security.ssl.EngineInputRecord.decrypt(EngineInputRecord.java:200)
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:968)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:901)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:775)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at com.github.kostyasha.yad.docker_java.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1080)
        at com.github.kostyasha.yad.docker_java.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:958)
        at com.github.kostyasha.yad.docker_java.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:895)
        at com.github.kostyasha.yad.docker_java.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
        ... 14 more
```

The weird thing is when I press `Test connection` in Jenkins I see the following in the docker log:

```
2016/08/02 13:39:46 http: TLS handshake error from 17.198.34.51:53559: tls: first record does not look like a TLS handshake
```

But we do use ` <tlsVerify>true</tlsVerify>` in our configuration.
[Cloud section of the Jenkins config: configOutput.xml.txt](https://github.com/KostyaSha/yet-another-docker-plugin/files/398124/configOutput.xml.txt)

Any ideas what's going on?

**Comment by KostyaSha** [comment]
`Test connection` is broken #53

**Comment by KostyaSha** [comment]
> protected by TLS.

How keys looks?

**Comment by KostyaSha** [comment]
What docker version and registry do you use?

**Comment by Mishail** [comment]
Mysteriously, as it started, the issue has gone now. I suspect it may be related to corrupted credentials, as I've reentered those key/certificates files again.
