### ISSUE TITLE
NullPointerException on provisioning

### ISSUE THREAD

**Issue by Reonaydo** [KostyaSha/yet-another-docker-plugin#80]
I get NullPointerException when start job that uses docker node.
Here com.github.kostyasha.yad log:
```
Sep 09, 2016 7:29:00 PM FINE com.github.kostyasha.yad.DockerProvisioningStrategy apply
Applying provisioning.
Sep 09, 2016 7:29:00 PM FINE com.github.kostyasha.yad.DockerProvisioningStrategy apply
Available capacity=0, currentDemand=1
Sep 09, 2016 7:29:00 PM INFO com.github.kostyasha.yad.DockerCloud provision
Asked to provision load: '1', for: 'centos7amd64docker' label
Sep 09, 2016 7:29:00 PM INFO com.github.kostyasha.yad.DockerCloud provision
Will provision 'centos-7', for label: 'centos7amd64docker', in cloud: 'dockerserver1'
Sep 09, 2016 7:29:00 PM FINE com.github.kostyasha.yad.client.ClientBuilderForConnector forConnector
Building connection to docker host 'tcp://172.31.240.69:4243'
Sep 09, 2016 7:29:00 PM INFO com.github.kostyasha.yad.DockerCloud addProvisionedSlave
Provisioning 'centos-7' number '0' on 'dockerserver1'; Total containers: '0'
Sep 09, 2016 7:29:00 PM FINE com.github.kostyasha.yad.DockerProvisioningStrategy apply
Planned 1 new nodes
Sep 09, 2016 7:29:00 PM FINE com.github.kostyasha.yad.DockerProvisioningStrategy apply
After 'com.github.kostyasha.yad.DockerCloud@1e0dda3[connector=com.github.kostyasha.yad.DockerConnector@2bdd614,provisionedImages={DockerSlaveTemplate[id=5a750a0a-5978-46e0-ac21-7d78d6e34648,labelString=centos7amd64docker,launcher=com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher@e8afc896,remoteFs=/root/,maxCapacity=2,mode=EXCLUSIVE,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@aa0178b[image=centos-7,pullImage=com.github.kostyasha.yad.commons.DockerPullImage@6bab9498,createContainer=DockerCreateContainer[command=,hostname=,dnsHosts=[],volumes=[],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=true,memoryLimit=0,cpuShares=<null>,privileged=false,tty=false,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=],stopContainer=com.github.kostyasha.yad.commons.DockerStopContainer@27f,removeContainer=com.github.kostyasha.yad.commons.DockerRemoveContainer@5b0f],nodeProperties=[]]=1},templates=[DockerSlaveTemplate[id=5a750a0a-5978-46e0-ac21-7d78d6e34648,labelString=centos7amd64docker,launcher=com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher@e8afc896,remoteFs=/root/,maxCapacity=2,mode=EXCLUSIVE,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@aa0178b[image=centos-7,pullImage=com.github.kostyasha.yad.commons.DockerPullImage@6bab9498,createContainer=DockerCreateContainer[command=,hostname=,dnsHosts=[],volumes=[],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=true,memoryLimit=0,cpuShares=<null>,privileged=false,tty=false,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=],stopContainer=com.github.kostyasha.yad.commons.DockerStopContainer@27f,removeContainer=com.github.kostyasha.yad.commons.DockerRemoveContainer@5b0f],nodeProperties=[]]],containerCap=50,name=dockerserver1]' provisioning, available capacity=1, currentDemand=1
Sep 09, 2016 7:29:00 PM FINE com.github.kostyasha.yad.DockerProvisioningStrategy apply
Provisioning completed
Sep 09, 2016 7:29:00 PM INFO com.github.kostyasha.yad.DockerCloud provisionWithWait
Trying to run container for centos-7
Sep 09, 2016 7:29:00 PM FINE com.github.kostyasha.yad.DockerCloud runContainer
Created container 575de1307d0cf636f375107860807c4678028f041930a0644760c57ab70ff50a, for dockerserver1
Sep 09, 2016 7:29:00 PM FINE com.github.kostyasha.yad.DockerCloud runContainer
Run container 575de1307d0cf636f375107860807c4678028f041930a0644760c57ab70ff50a, for dockerserver1
Sep 09, 2016 7:29:00 PM FINE com.github.kostyasha.yad.DockerCloud provisionWithWait
Container 575de1307d0cf636f375107860807c4678028f041930a0644760c57ab70ff50a is ready for ssh slave connection
Sep 09, 2016 7:29:00 PM SEVERE com.github.kostyasha.yad.DockerCloud lambda$provision$0
Error in provisioning; template='DockerSlaveTemplate[id=5a750a0a-5978-46e0-ac21-7d78d6e34648,labelString=centos7amd64docker,launcher=com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher@e8afc896,remoteFs=/root/,maxCapacity=2,mode=EXCLUSIVE,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@aa0178b[image=centos-7,pullImage=com.github.kostyasha.yad.commons.DockerPullImage@6bab9498,createContainer=DockerCreateContainer[command=,hostname=,dnsHosts=[],volumes=[],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=true,memoryLimit=0,cpuShares=<null>,privileged=false,tty=false,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=],stopContainer=com.github.kostyasha.yad.commons.DockerStopContainer@27f,removeContainer=com.github.kostyasha.yad.commons.DockerRemoveContainer@5b0f],nodeProperties=[]]' for cloud='dockerserver1'
java.lang.NullPointerException
	at java.util.TreeMap.getEntry(TreeMap.java:347)
	at java.util.TreeMap.containsKey(TreeMap.java:232)
	at jenkinsci.plugin.browseraxis.label.BrowserFinder.checkNodes(BrowserFinder.java:44)
	at jenkinsci.plugin.browseraxis.label.BrowserFinder.findLabels(BrowserFinder.java:72)
	at hudson.model.Node.getDynamicLabels(Node.java:309)
	at hudson.model.Node.getAssignedLabels(Node.java:294)
	at hudson.model.Slave.<init>(Slave.java:185)
	at hudson.slaves.AbstractCloudSlave.<init>(AbstractCloudSlave.java:51)
	at com.github.kostyasha.yad.DockerSlave.<init>(DockerSlave.java:58)
	at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:227)
	at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:120)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by KostyaSha** [comment]
It looks like the issue caused by https://github.com/jenkinsci/browser-axis-plugin , they have some changes in master, but they didn't release it.

**Comment by Reonaydo** [comment]
@KostyaSha thank you! I will try without browser-axis plugin
