### ISSUE TITLE
Authentication error when authenticate to pull an image

### ISSUE THREAD

**Issue by ppadialitrs** [KostyaSha/yet-another-docker-plugin#85]
Hi
i have a docker container configured in a private registry, but im getting an authentication error when i set `Pull always`.
The username and password is OK, at least my docker login command is done OK from command line.

The log is:

```
onError
Error during callback
com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.exception.InternalServerErrorException: Get https://myrepositoryURL/v2/mycontainer/tags/list: unknown: Authentication is required

    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Sep 15, 2016 7:27:18 PM SEVERE com.github.kostyasha.yad.DockerCloud lambda$provision$0
Error in provisioning; template='DockerSlaveTemplate[id=517fad34-52aa-4624-b1fc-88ff19e1bae2,labelString=jsdt-build-slave,launcher=com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher@133e5f4a,remoteFs=/home/jenkins,maxCapacity=10,mode=EXCLUSIVE,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@36be9cad[image=myrepo/jsdt_build_slave,pullImage=com.github.kostyasha.yad.commons.DockerPullImage@3529acc0,createContainer=DockerCreateContainer[command=,hostname=,dnsHosts=[],volumes=[],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=false,memoryLimit=0,cpuShares=<null>,privileged=false,tty=false,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=],stopContainer=com.github.kostyasha.yad.commons.DockerStopContainer@27f,removeContainer=com.github.kostyasha.yad.commons.DockerRemoveContainer@5b0f],nodeProperties=[]]' for cloud='local docker'
com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.exception.InternalServerErrorException: Get https://myrepourl/v2/jsdt_build_slave/tags/list: unknown: Authentication is required

    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
    at com.github.kostyasha.yad_docker_java.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by ppadialitrs** [comment]
Hi all, i think i found the Bug, my password contains characters like "?) 
i have create an account with only digits and letters and now is working properly, looks like a bug or limitation

**Comment by KostyaSha** [comment]
Very strange...

**Comment by KostyaSha** [comment]
AFAIK registry has no auth backend, what do you use? That sounds similar to https://github.com/docker-java/docker-java/issues/691 Could you try curl for custom check? 
Dumping http traffic between with header verification should also very help.
