### ISSUE TITLE
Specifying links under "Create Container Settings"?

### ISSUE THREAD

**Issue by gcbartlett** [KostyaSha/yet-another-docker-plugin#91]
Is there a way to specify links to other containers (`docker create --link value1 --link value2 ...`) when creating the container to be used by YADP (0.1.0-rc24)?  My created container needs access to another docker container's hostname.

Is there a way to use the `Docker Command` field to specify arbitrary arguments?  (I wasn't clear what this field is used for; I didn't understand the help text referring to Jenkins Launchers).  Unless this refers to the command run in the created container, in which case this isn't relevant.

Maybe instead of looking for links, I can achieve the same thing using a shared docker network with service discovery.

Thanks!

**Comment by KostyaSha** [comment]
`-link value                  Add link to another container (default [])`
Is it only String value or you need to do additional actions before?

**Comment by gcbartlett** [comment]
I think it is just a string (it becomes a hosts file alias on the created container), but the argument can be repeated multiple times to end up with an array of Strings.

**Comment by KostyaSha** [comment]
It missing now in yad, it available in docker-java https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/command/CreateContainerCmd.java#L340. I will try add.

**Comment by gcbartlett** [comment]
That's it.  Thank you!

**Comment by KostyaSha** [comment]
https://github.com/KostyaSha/yet-another-docker-plugin/pull/92

**Comment by KostyaSha** [comment]
Released, please try.

**Comment by gcbartlett** [comment]
Thanks @KostyaSha. I updated the YAD plugin to the new **0.1.0-rc25** release and restarted Jenkins, but when I try to change the "Create Container Settings", I don't see the newly added "**Links**" field.  I was expecting to see it just below the "Cpuset constraint: MEMs" field, but that is still the last field in the section.  I've tried restarting and refreshing the configuration pages several times, and deleting and recreating the Docker Template and Cloud blocks.  Is there a step I'm missing?

**Comment by KostyaSha** [comment]
Are you sure that you updated to `-rc25`? please open `http://yourjenkins/about` page.

**Comment by gcbartlett** [comment]
That's what I was expecting to see too @KostyaSha, but this is what I see (even after uninstalling the plugin, deleting the old configuration file, and reinstalling the `-rc25` version:

![jenkins-about](https://cloud.githubusercontent.com/assets/4016279/19015083/e61f4930-87b1-11e6-85e0-ef54d4f622c8.gif)

![yad-config](https://cloud.githubusercontent.com/assets/4016279/19015094/22ac974a-87b2-11e6-9ab9-1a07a7db42f4.gif)

Weird!

**Comment by KostyaSha** [comment]
Could you stop jenkins, remove plugins/yet-another-docker-plugin directory and hpis, download fresh and place here and run jenkins?

**Comment by gcbartlett** [comment]
I'm sorry to report that after stopping, manually removing all YAD plugin directories, and downloading new versions repeatedly (both from Maven Central and the hpi file directly), I still don't see the `Links` field (I've also tried various browsers) when I try to add/configure a new YAD cloud/template. :-(

Is it possible that the various plugin repos have an older version of -rc25 before you added the Links feature?  Can you send me directly the hpi file you were testing with?

**Comment by KostyaSha** [comment]
I will test more and reply.

2016-10-01 21:30 GMT+04:00 Gary Bartlett <notifications@github.com>:

**Comment by KostyaSha** [comment]
reproduced, shit happened with release from wrong branch.

**Comment by KostyaSha** [comment]
And now? :)

**Comment by gcbartlett** [comment]
That did the trick, thanks @KostyaSha!

It appears, though, that docker-java does not support the `--link <name or id>` form, but only the `--link <name or id>:alias` form (see https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/).  Passing a single container name leads to an `IllegalArgumentException`:

```
Oct 02, 2016 1:02:12 AM com.github.kostyasha.yad.DockerCloud provision
INFO: Asked to provision load: '1', for: 'docker' label
Oct 02, 2016 1:02:12 AM com.github.kostyasha.yad.DockerCloud provision
INFO: Will provision 'jenkins_slave', for label: 'docker', in cloud: 'Docker Cloud'
Oct 02, 2016 1:02:12 AM com.github.kostyasha.yad.DockerCloud addProvisionedSlave
INFO: Provisioning 'jenkins_slave' number '0' on 'Docker Cloud'; Total containers: '0'
Oct 02, 2016 1:02:12 AM com.github.kostyasha.yad.DockerCloud provisionWithWait
INFO: Trying to run container for jenkins_slave
Oct 02, 2016 1:02:12 AM com.github.kostyasha.yad.DockerCloud lambda$provision$0
SEVERE: Error in provisioning; template='DockerSlaveTemplate[id=9885ba47-5145-4b42-b431-eb51d07909c9,labelString=docker,launcher=com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher@b548dce0,remoteFs=/home/jenkins,maxCapacity=5,mode=EXCLUSIVE,retentionStrategy=com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy@27f,numExecutors=1,dockerContainerLifecycle=com.github.kostyasha.yad.DockerContainerLifecycle@4d8bf65c[image=jenkins_slave,pullImage=com.github.kostyasha.yad.commons.DockerPullImage@e3fd4439,createContainer=DockerCreateContainer[command=,hostname=,dnsHosts=[],volumes=[],volumesFrom=[],environment=[],bindPorts=,bindAllPorts=false,memoryLimit=0,cpuShares=<null>,privileged=false,tty=false,macAddress=<null>,extraHosts=[],networkMode=<null>,devices=[],cpusetCpus=,cpusetMems=,links=[jenkins_master_1]],stopContainer=com.github.kostyasha.yad.commons.DockerStopContainer@27f,removeContainer=com.github.kostyasha.yad.commons.DockerRemoveContainer@5aea],nodeProperties=[]]' for cloud='Docker Cloud'
java.lang.IllegalArgumentException: Error parsing Link 'jenkins_master_1'
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.model.Link.parse(Link.java:70)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.github.kostyasha.yad.commons.DockerCreateContainer.fillContainerConfig(DockerCreateContainer.java:541)
	at com.github.kostyasha.yad.DockerCloud.runContainer(DockerCloud.java:151)
	at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:197)
	at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:120)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Oct 02, 2016 1:02:22 AM hudson.slaves.NodeProvisioner$2 run
WARNING: Provisioned agent jenkins_slave failed to launch
java.lang.IllegalArgumentException: Error parsing Link 'jenkins_master_1'
	at com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.model.Link.parse(Link.java:70)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.github.kostyasha.yad.commons.DockerCreateContainer.fillContainerConfig(DockerCreateContainer.java:541)
	at com.github.kostyasha.yad.DockerCloud.runContainer(DockerCloud.java:151)
	at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:197)
	at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:120)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I can easily work around that, though.  Thank you again!

**Comment by KostyaSha** [comment]
@gcbartlett i will add UI verification and you can check/open issue in docker-java, then it will appear in yad.

**Comment by gcbartlett** [comment]
Thanks, I created https://github.com/docker-java/docker-java/issues/718.
